;;; -*- Mode: Lisp; -*-

;;; File created by Expresso 4.0.0 (compiled 2012-Apr-11 16:38)
;;; Date created: 2012-04-11 16:48:28
;;; Compilation of /home/pdenno/projects/sei/projects/15926-2/15926-2.exp

(error "DON'T USE THIS FILE. USE THE ONE IN /local/lisp/pod-utils/uml-utils/models/cre.")

(in-package :AP233)

(SETF (SCHEMA *EXPRESSO*)
      (ENSURE-SCHEMA 'EXPRESS-SCHEMA
                     :NAME
                     "lifecycle_integration_schema"
                     :LISP-PACKAGE
                     :AP233
                     :INTERNED-NAME
                     '|lifecycle_integration_schema|
                     :SCHEMA-PATHNAME
                     #P"/home/pdenno/projects/sei/projects/15926-2/15926-2.exp"))
(EXPO::CLEAR-SCHEMA (FIND-SCHEMA "lifecycle_integration_schema"))
(MAPCAR #'SHADOW-FOR-MODEL '("CLASS" "DEFINITION" "PHASE" "STREAM"))


;;;=================
;;; SpecializedTypes
;;;=================


;;;=================
;;; EntityTypes
;;;=================
(DEFENTITY-CLASS "ABSTRACT_OBJECT" :LIFECYCLE_INTEGRATION_SCHEMA NIL)

(SETF (SUBTYPE-OF (FIND-CLASS 'ABSTRACT_OBJECT)) '(THING))
(SETF (EXPO::ABSTRACT-P (FIND-CLASS 'ABSTRACT_OBJECT)) T)


(DEFENTITY-CLASS "ACTIVITY" :LIFECYCLE_INTEGRATION_SCHEMA NIL)

(SETF (SUBTYPE-OF (FIND-CLASS 'ACTIVITY)) '(POSSIBLE_INDIVIDUAL))


(DEFENTITY-CLASS "ACTUAL_INDIVIDUAL" :LIFECYCLE_INTEGRATION_SCHEMA NIL)

(SETF (SUBTYPE-OF (FIND-CLASS 'ACTUAL_INDIVIDUAL))
      '(POSSIBLE_INDIVIDUAL))


(DEFENTITY-CLASS "APPROVAL" :LIFECYCLE_INTEGRATION_SCHEMA
  (("approved" :RANGE RELATIONSHIP :SOURCE APPROVAL :OPTIONAL NIL)
   ("approver"
    :RANGE
    POSSIBLE_INDIVIDUAL
    :SOURCE
    APPROVAL
    :OPTIONAL
    NIL)))

(SETF (SUBTYPE-OF (FIND-CLASS 'APPROVAL)) '(RELATIONSHIP))


(DEFENTITY-CLASS "ARITHMETIC_NUMBER" :LIFECYCLE_INTEGRATION_SCHEMA NIL)

(SETF (SUBTYPE-OF (FIND-CLASS 'ARITHMETIC_NUMBER)) '(CLASS_OF_CLASS))


(DEFENTITY-CLASS "ARRANGED_INDIVIDUAL" :LIFECYCLE_INTEGRATION_SCHEMA
  NIL)

(SETF (SUBTYPE-OF (FIND-CLASS 'ARRANGED_INDIVIDUAL))
      '(POSSIBLE_INDIVIDUAL))


(DEFENTITY-CLASS "ARRANGEMENT_OF_INDIVIDUAL"
                 :LIFECYCLE_INTEGRATION_SCHEMA
  (("whole"
    :RANGE
    ARRANGED_INDIVIDUAL
    :SOURCE
    COMPOSITION_OF_INDIVIDUAL
    :REDEFINITION-OF
    (COMPOSITION_OF_INDIVIDUAL "whole")
    :OPTIONAL
    NIL)))

(SETF (SUBTYPE-OF (FIND-CLASS 'ARRANGEMENT_OF_INDIVIDUAL))
      '(COMPOSITION_OF_INDIVIDUAL))


(DEFENTITY-CLASS "ASSEMBLY_OF_INDIVIDUAL" :LIFECYCLE_INTEGRATION_SCHEMA
  NIL)

(SETF (SUBTYPE-OF (FIND-CLASS 'ASSEMBLY_OF_INDIVIDUAL))
      '(ARRANGEMENT_OF_INDIVIDUAL))


(DEFENTITY-CLASS "BEGINNING" :LIFECYCLE_INTEGRATION_SCHEMA NIL)

(SETF (SUBTYPE-OF (FIND-CLASS 'BEGINNING)) '(TEMPORAL_BOUNDING))


(DEFENTITY-CLASS "BOUNDARY_OF_NUMBER_SPACE"
                 :LIFECYCLE_INTEGRATION_SCHEMA
  (("subclass"
    :RANGE
    NUMBER_SPACE
    :SOURCE
    SPECIALIZATION
    :REDEFINITION-OF
    (SPECIALIZATION "subclass")
    :OPTIONAL
    NIL)
   ("superclass"
    :RANGE
    NUMBER_SPACE
    :SOURCE
    SPECIALIZATION
    :REDEFINITION-OF
    (SPECIALIZATION "superclass")
    :OPTIONAL
    NIL)))

(SETF (SUBTYPE-OF (FIND-CLASS 'BOUNDARY_OF_NUMBER_SPACE))
      '(SPECIALIZATION))


(DEFENTITY-CLASS "BOUNDARY_OF_PROPERTY_SPACE"
                 :LIFECYCLE_INTEGRATION_SCHEMA
  (("subclass"
    :RANGE
    PROPERTY_SPACE
    :SOURCE
    SPECIALIZATION
    :REDEFINITION-OF
    (SPECIALIZATION "subclass")
    :OPTIONAL
    NIL)
   ("superclass"
    :RANGE
    PROPERTY_SPACE
    :SOURCE
    SPECIALIZATION
    :REDEFINITION-OF
    (SPECIALIZATION "superclass")
    :OPTIONAL
    NIL)))

(SETF (SUBTYPE-OF (FIND-CLASS 'BOUNDARY_OF_PROPERTY_SPACE))
      '(SPECIALIZATION))


(DEFENTITY-CLASS "CARDINALITY" :LIFECYCLE_INTEGRATION_SCHEMA
  (("maximum_cardinality"
    :RANGE
    (MAKE-INSTANCE 'INTEGER-TYP)
    :SOURCE
    CARDINALITY
    :OPTIONAL
    T)
   ("minimum_cardinality"
    :RANGE
    (MAKE-INSTANCE 'INTEGER-TYP)
    :SOURCE
    CARDINALITY
    :OPTIONAL
    T)))

(SETF (SUBTYPE-OF (FIND-CLASS 'CARDINALITY)) '(CLASS))


(DEFENTITY-CLASS "CAUSE_OF_EVENT" :LIFECYCLE_INTEGRATION_SCHEMA
  (("caused" :RANGE EVENT :SOURCE CAUSE_OF_EVENT :OPTIONAL NIL)
   ("causer" :RANGE ACTIVITY :SOURCE CAUSE_OF_EVENT :OPTIONAL NIL)))

(SETF (SUBTYPE-OF (FIND-CLASS 'CAUSE_OF_EVENT)) '(RELATIONSHIP))


(DEFENTITY-CLASS "CLASS" :LIFECYCLE_INTEGRATION_SCHEMA NIL)

(SETF (SUBTYPE-OF (FIND-CLASS 'CLASS)) '(ABSTRACT_OBJECT))


(DEFENTITY-CLASS "CLASS_OF_ABSTRACT_OBJECT"
                 :LIFECYCLE_INTEGRATION_SCHEMA
  NIL)

(SETF (SUBTYPE-OF (FIND-CLASS 'CLASS_OF_ABSTRACT_OBJECT)) '(CLASS))
(SETF (EXPO::ABSTRACT-P (FIND-CLASS 'CLASS_OF_ABSTRACT_OBJECT)) T)


(DEFENTITY-CLASS "CLASS_OF_ACTIVITY" :LIFECYCLE_INTEGRATION_SCHEMA NIL)

(SETF (SUBTYPE-OF (FIND-CLASS 'CLASS_OF_ACTIVITY))
      '(CLASS_OF_ARRANGED_INDIVIDUAL))


(DEFENTITY-CLASS "CLASS_OF_APPROVAL" :LIFECYCLE_INTEGRATION_SCHEMA
  (("class_of_approved"
    :RANGE
    CLASS_OF_RELATIONSHIP
    :SOURCE
    CLASS_OF_APPROVAL
    :OPTIONAL
    NIL)
   ("class_of_approver"
    :RANGE
    CLASS_OF_INDIVIDUAL
    :SOURCE
    CLASS_OF_APPROVAL
    :OPTIONAL
    NIL)))

(SETF (SUBTYPE-OF (FIND-CLASS 'CLASS_OF_APPROVAL))
      '(CLASS_OF_RELATIONSHIP))


(DEFENTITY-CLASS "CLASS_OF_APPROVAL_BY_STATUS"
                 :LIFECYCLE_INTEGRATION_SCHEMA
  NIL)

(SETF (SUBTYPE-OF (FIND-CLASS 'CLASS_OF_APPROVAL_BY_STATUS))
      '(CLASS_OF_RELATIONSHIP))


(DEFENTITY-CLASS "CLASS_OF_ARRANGED_INDIVIDUAL"
                 :LIFECYCLE_INTEGRATION_SCHEMA
  NIL)

(SETF (SUBTYPE-OF (FIND-CLASS 'CLASS_OF_ARRANGED_INDIVIDUAL))
      '(CLASS_OF_INDIVIDUAL))


(DEFENTITY-CLASS "CLASS_OF_ARRANGEMENT_OF_INDIVIDUAL"
                 :LIFECYCLE_INTEGRATION_SCHEMA
  (("class_of_whole"
    :RANGE
    CLASS_OF_ARRANGED_INDIVIDUAL
    :SOURCE
    CLASS_OF_COMPOSITION_OF_INDIVIDUAL
    :REDEFINITION-OF
    (CLASS_OF_COMPOSITION_OF_INDIVIDUAL "class_of_whole")
    :OPTIONAL
    NIL)))

(SETF (SUBTYPE-OF (FIND-CLASS 'CLASS_OF_ARRANGEMENT_OF_INDIVIDUAL))
      '(CLASS_OF_COMPOSITION_OF_INDIVIDUAL))


(DEFENTITY-CLASS "CLASS_OF_ASSEMBLY_OF_INDIVIDUAL"
                 :LIFECYCLE_INTEGRATION_SCHEMA
  NIL)

(SETF (SUBTYPE-OF (FIND-CLASS 'CLASS_OF_ASSEMBLY_OF_INDIVIDUAL))
      '(CLASS_OF_ARRANGEMENT_OF_INDIVIDUAL))


(DEFENTITY-CLASS "CLASS_OF_ASSERTION" :LIFECYCLE_INTEGRATION_SCHEMA NIL)

(SETF (SUBTYPE-OF (FIND-CLASS 'CLASS_OF_ASSERTION))
      '(CLASS_OF_RELATIONSHIP))


(DEFENTITY-CLASS "CLASS_OF_ATOM" :LIFECYCLE_INTEGRATION_SCHEMA NIL)

(SETF (SUBTYPE-OF (FIND-CLASS 'CLASS_OF_ATOM))
      '(CLASS_OF_ARRANGED_INDIVIDUAL))


(DEFENTITY-CLASS "CLASS_OF_BIOLOGICAL_MATTER"
                 :LIFECYCLE_INTEGRATION_SCHEMA
  NIL)

(SETF (SUBTYPE-OF (FIND-CLASS 'CLASS_OF_BIOLOGICAL_MATTER))
      '(CLASS_OF_ARRANGED_INDIVIDUAL))


(DEFENTITY-CLASS "CLASS_OF_CAUSE_OF_BEGINNING_OF_CLASS_OF_INDIVIDUAL"
                 :LIFECYCLE_INTEGRATION_SCHEMA
  (("class_of_begun"
    :RANGE
    CLASS_OF_INDIVIDUAL
    :SOURCE
    CLASS_OF_CAUSE_OF_BEGINNING_OF_CLASS_OF_INDIVIDUAL
    :OPTIONAL
    NIL)
   ("class_of_causer"
    :RANGE
    CLASS_OF_ACTIVITY
    :SOURCE
    CLASS_OF_CAUSE_OF_BEGINNING_OF_CLASS_OF_INDIVIDUAL
    :OPTIONAL
    NIL)))

(SETF (SUBTYPE-OF (FIND-CLASS 'CLASS_OF_CAUSE_OF_BEGINNING_OF_CLASS_OF_INDIVIDUAL))
      '(CLASS_OF_RELATIONSHIP))


(DEFENTITY-CLASS "CLASS_OF_CAUSE_OF_ENDING_OF_CLASS_OF_INDIVIDUAL"
                 :LIFECYCLE_INTEGRATION_SCHEMA
  (("class_of_causer"
    :RANGE
    CLASS_OF_ACTIVITY
    :SOURCE
    CLASS_OF_CAUSE_OF_ENDING_OF_CLASS_OF_INDIVIDUAL
    :OPTIONAL
    NIL)
   ("class_of_ended"
    :RANGE
    CLASS_OF_INDIVIDUAL
    :SOURCE
    CLASS_OF_CAUSE_OF_ENDING_OF_CLASS_OF_INDIVIDUAL
    :OPTIONAL
    NIL)))

(SETF (SUBTYPE-OF (FIND-CLASS 'CLASS_OF_CAUSE_OF_ENDING_OF_CLASS_OF_INDIVIDUAL))
      '(CLASS_OF_RELATIONSHIP))


(DEFENTITY-CLASS "CLASS_OF_CLASS" :LIFECYCLE_INTEGRATION_SCHEMA NIL)

(SETF (SUBTYPE-OF (FIND-CLASS 'CLASS_OF_CLASS))
      '(CLASS_OF_ABSTRACT_OBJECT))


(DEFENTITY-CLASS "CLASS_OF_CLASS_OF_COMPOSITION"
                 :LIFECYCLE_INTEGRATION_SCHEMA
  (("class_of_class_of_part"
    :RANGE
    CLASS_OF_CLASS_OF_INDIVIDUAL
    :SOURCE
    CLASS_OF_CLASS_OF_COMPOSITION
    :OPTIONAL
    NIL)
   ("class_of_class_of_whole"
    :RANGE
    CLASS_OF_CLASS_OF_INDIVIDUAL
    :SOURCE
    CLASS_OF_CLASS_OF_COMPOSITION
    :OPTIONAL
    NIL)))

(SETF (SUBTYPE-OF (FIND-CLASS 'CLASS_OF_CLASS_OF_COMPOSITION))
      '(CLASS_OF_CLASS_OF_RELATIONSHIP))


(DEFENTITY-CLASS "CLASS_OF_CLASS_OF_DEFINITION"
                 :LIFECYCLE_INTEGRATION_SCHEMA
  NIL)

(SETF (SUBTYPE-OF (FIND-CLASS 'CLASS_OF_CLASS_OF_DEFINITION))
      '(CLASS_OF_CLASS_OF_REPRESENTATION))


(DEFENTITY-CLASS "CLASS_OF_CLASS_OF_DESCRIPTION"
                 :LIFECYCLE_INTEGRATION_SCHEMA
  NIL)

(SETF (SUBTYPE-OF (FIND-CLASS 'CLASS_OF_CLASS_OF_DESCRIPTION))
      '(CLASS_OF_CLASS_OF_REPRESENTATION))


(DEFENTITY-CLASS "CLASS_OF_CLASS_OF_IDENTIFICATION"
                 :LIFECYCLE_INTEGRATION_SCHEMA
  NIL)

(SETF (SUBTYPE-OF (FIND-CLASS 'CLASS_OF_CLASS_OF_IDENTIFICATION))
      '(CLASS_OF_CLASS_OF_REPRESENTATION))


(DEFENTITY-CLASS "CLASS_OF_CLASS_OF_INDIVIDUAL"
                 :LIFECYCLE_INTEGRATION_SCHEMA
  NIL)

(SETF (SUBTYPE-OF (FIND-CLASS 'CLASS_OF_CLASS_OF_INDIVIDUAL))
      '(CLASS_OF_CLASS))


(DEFENTITY-CLASS "CLASS_OF_CLASS_OF_INFORMATION_REPRESENTATION"
                 :LIFECYCLE_INTEGRATION_SCHEMA
  NIL)

(SETF (SUBTYPE-OF (FIND-CLASS 'CLASS_OF_CLASS_OF_INFORMATION_REPRESENTATION))
      '(CLASS_OF_CLASS_OF_INDIVIDUAL))


(DEFENTITY-CLASS "CLASS_OF_CLASS_OF_RELATIONSHIP"
                 :LIFECYCLE_INTEGRATION_SCHEMA
  NIL)

(SETF (SUBTYPE-OF (FIND-CLASS 'CLASS_OF_CLASS_OF_RELATIONSHIP))
      '(CLASS_OF_CLASS))


(DEFENTITY-CLASS "CLASS_OF_CLASS_OF_RELATIONSHIP_WITH_SIGNATURE"
                 :LIFECYCLE_INTEGRATION_SCHEMA
  NIL)

(SETF (SUBTYPE-OF (FIND-CLASS 'CLASS_OF_CLASS_OF_RELATIONSHIP_WITH_SIGNATURE))
      '(CLASS_OF_CLASS_OF_RELATIONSHIP
        CLASS_OF_RELATIONSHIP_WITH_SIGNATURE))


(DEFENTITY-CLASS "CLASS_OF_CLASS_OF_REPRESENTATION"
                 :LIFECYCLE_INTEGRATION_SCHEMA
  (("class_of_pattern"
    :RANGE
    CLASS_OF_CLASS_OF_INFORMATION_REPRESENTATION
    :SOURCE
    CLASS_OF_CLASS_OF_REPRESENTATION
    :OPTIONAL
    NIL)
   ("class_of_represented"
    :RANGE
    CLASS
    :SOURCE
    CLASS_OF_CLASS_OF_REPRESENTATION
    :OPTIONAL
    NIL)))

(SETF (SUBTYPE-OF (FIND-CLASS 'CLASS_OF_CLASS_OF_REPRESENTATION))
      '(CLASS_OF_CLASS_OF_RELATIONSHIP))


(DEFENTITY-CLASS "CLASS_OF_CLASS_OF_REPRESENTATION_TRANSLATION"
                 :LIFECYCLE_INTEGRATION_SCHEMA
  (("class_of_first"
    :RANGE
    CLASS_OF_CLASS_OF_INFORMATION_REPRESENTATION
    :SOURCE
    CLASS_OF_CLASS_OF_REPRESENTATION_TRANSLATION
    :OPTIONAL
    NIL)
   ("class_of_second"
    :RANGE
    CLASS_OF_CLASS_OF_INFORMATION_REPRESENTATION
    :SOURCE
    CLASS_OF_CLASS_OF_REPRESENTATION_TRANSLATION
    :OPTIONAL
    NIL)))

(SETF (SUBTYPE-OF (FIND-CLASS 'CLASS_OF_CLASS_OF_REPRESENTATION_TRANSLATION))
      '(CLASS_OF_CLASS_OF_RELATIONSHIP))


(DEFENTITY-CLASS "CLASS_OF_CLASS_OF_RESPONSIBILITY_FOR_REPRESENTATION"
                 :LIFECYCLE_INTEGRATION_SCHEMA
  (("class_of_class_of_controlled"
    :RANGE
    CLASS_OF_CLASS_OF_REPRESENTATION
    :SOURCE
    CLASS_OF_CLASS_OF_RESPONSIBILITY_FOR_REPRESENTATION
    :OPTIONAL
    NIL)
   ("controller"
    :RANGE
    POSSIBLE_INDIVIDUAL
    :SOURCE
    CLASS_OF_CLASS_OF_RESPONSIBILITY_FOR_REPRESENTATION
    :OPTIONAL
    NIL)))

(SETF (SUBTYPE-OF (FIND-CLASS 'CLASS_OF_CLASS_OF_RESPONSIBILITY_FOR_REPRESENTATION))
      '(CLASS_OF_CLASS_OF_RELATIONSHIP))


(DEFENTITY-CLASS "CLASS_OF_CLASS_OF_USAGE_OF_REPRESENTATION"
                 :LIFECYCLE_INTEGRATION_SCHEMA
  (("class_of_class_of_used"
    :RANGE
    CLASS_OF_CLASS_OF_REPRESENTATION
    :SOURCE
    CLASS_OF_CLASS_OF_USAGE_OF_REPRESENTATION
    :OPTIONAL
    NIL)
   ("user"
    :RANGE
    POSSIBLE_INDIVIDUAL
    :SOURCE
    CLASS_OF_CLASS_OF_USAGE_OF_REPRESENTATION
    :OPTIONAL
    NIL)))

(SETF (SUBTYPE-OF (FIND-CLASS 'CLASS_OF_CLASS_OF_USAGE_OF_REPRESENTATION))
      '(CLASS_OF_CLASS_OF_RELATIONSHIP))


(DEFENTITY-CLASS "CLASS_OF_CLASSIFICATION"
                 :LIFECYCLE_INTEGRATION_SCHEMA
  (("class_of_classified"
    :RANGE
    CLASS
    :SOURCE
    CLASS_OF_CLASSIFICATION
    :OPTIONAL
    NIL)
   ("class_of_classifier"
    :RANGE
    CLASS_OF_CLASS
    :SOURCE
    CLASS_OF_CLASSIFICATION
    :OPTIONAL
    NIL)))

(SETF (SUBTYPE-OF (FIND-CLASS 'CLASS_OF_CLASSIFICATION))
      '(CLASS_OF_RELATIONSHIP))


(DEFENTITY-CLASS "CLASS_OF_COMPOSITE_MATERIAL"
                 :LIFECYCLE_INTEGRATION_SCHEMA
  NIL)

(SETF (SUBTYPE-OF (FIND-CLASS 'CLASS_OF_COMPOSITE_MATERIAL))
      '(CLASS_OF_ARRANGED_INDIVIDUAL))


(DEFENTITY-CLASS "CLASS_OF_COMPOSITION_OF_INDIVIDUAL"
                 :LIFECYCLE_INTEGRATION_SCHEMA
  (("class_of_part"
    :RANGE
    CLASS_OF_INDIVIDUAL
    :SOURCE
    CLASS_OF_COMPOSITION_OF_INDIVIDUAL
    :OPTIONAL
    NIL)
   ("class_of_whole"
    :RANGE
    CLASS_OF_INDIVIDUAL
    :SOURCE
    CLASS_OF_COMPOSITION_OF_INDIVIDUAL
    :OPTIONAL
    NIL)))

(SETF (SUBTYPE-OF (FIND-CLASS 'CLASS_OF_COMPOSITION_OF_INDIVIDUAL))
      '(CLASS_OF_RELATIONSHIP))


(DEFENTITY-CLASS "CLASS_OF_COMPOUND" :LIFECYCLE_INTEGRATION_SCHEMA NIL)

(SETF (SUBTYPE-OF (FIND-CLASS 'CLASS_OF_COMPOUND))
      '(CLASS_OF_ARRANGED_INDIVIDUAL))


(DEFENTITY-CLASS "CLASS_OF_CONNECTION_OF_INDIVIDUAL"
                 :LIFECYCLE_INTEGRATION_SCHEMA
  (("class_of_side_1"
    :RANGE
    CLASS_OF_INDIVIDUAL
    :SOURCE
    CLASS_OF_CONNECTION_OF_INDIVIDUAL
    :OPTIONAL
    NIL)
   ("class_of_side_2"
    :RANGE
    CLASS_OF_INDIVIDUAL
    :SOURCE
    CLASS_OF_CONNECTION_OF_INDIVIDUAL
    :OPTIONAL
    NIL)))

(SETF (SUBTYPE-OF (FIND-CLASS 'CLASS_OF_CONNECTION_OF_INDIVIDUAL))
      '(CLASS_OF_RELATIONSHIP))
(SETF (EXPO::ABSTRACT-P (FIND-CLASS 'CLASS_OF_CONNECTION_OF_INDIVIDUAL))
      T)


(DEFENTITY-CLASS "CLASS_OF_CONTAINMENT_OF_INDIVIDUAL"
                 :LIFECYCLE_INTEGRATION_SCHEMA
  NIL)

(SETF (SUBTYPE-OF (FIND-CLASS 'CLASS_OF_CONTAINMENT_OF_INDIVIDUAL))
      '(CLASS_OF_RELATIVE_LOCATION))


(DEFENTITY-CLASS "CLASS_OF_DEFINITION" :LIFECYCLE_INTEGRATION_SCHEMA
  (("represented"
    :RANGE
    CLASS
    :SOURCE
    CLASS_OF_REPRESENTATION_OF_THING
    :REDEFINITION-OF
    (CLASS_OF_REPRESENTATION_OF_THING "represented")
    :OPTIONAL
    NIL)))

(SETF (SUBTYPE-OF (FIND-CLASS 'CLASS_OF_DEFINITION))
      '(CLASS_OF_REPRESENTATION_OF_THING))


(DEFENTITY-CLASS "CLASS_OF_DESCRIPTION" :LIFECYCLE_INTEGRATION_SCHEMA
  NIL)

(SETF (SUBTYPE-OF (FIND-CLASS 'CLASS_OF_DESCRIPTION))
      '(CLASS_OF_REPRESENTATION_OF_THING))


(DEFENTITY-CLASS "CLASS_OF_DIMENSION_FOR_SHAPE"
                 :LIFECYCLE_INTEGRATION_SCHEMA
  (("class_of_dimension"
    :RANGE
    CLASS_OF_SHAPE_DIMENSION
    :SOURCE
    CLASS_OF_DIMENSION_FOR_SHAPE
    :OPTIONAL
    NIL)
   ("class_of_shape"
    :RANGE
    CLASS_OF_SHAPE
    :SOURCE
    CLASS_OF_DIMENSION_FOR_SHAPE
    :OPTIONAL
    NIL)))

(SETF (SUBTYPE-OF (FIND-CLASS 'CLASS_OF_DIMENSION_FOR_SHAPE))
      '(CLASS_OF_CLASS_OF_RELATIONSHIP))


(DEFENTITY-CLASS "CLASS_OF_DIRECT_CONNECTION"
                 :LIFECYCLE_INTEGRATION_SCHEMA
  NIL)

(SETF (SUBTYPE-OF (FIND-CLASS 'CLASS_OF_DIRECT_CONNECTION))
      '(CLASS_OF_CONNECTION_OF_INDIVIDUAL))


(DEFENTITY-CLASS "CLASS_OF_EVENT" :LIFECYCLE_INTEGRATION_SCHEMA NIL)

(SETF (SUBTYPE-OF (FIND-CLASS 'CLASS_OF_EVENT)) '(CLASS_OF_INDIVIDUAL))


(DEFENTITY-CLASS "CLASS_OF_EXPRESS_INFORMATION_REPRESENTATION"
                 :LIFECYCLE_INTEGRATION_SCHEMA
  NIL)

(SETF (SUBTYPE-OF (FIND-CLASS 'CLASS_OF_EXPRESS_INFORMATION_REPRESENTATION))
      '(CLASS_OF_INFORMATION_REPRESENTATION))
(SETF (EXPO::ABSTRACT-P (FIND-CLASS 'CLASS_OF_EXPRESS_INFORMATION_REPRESENTATION))
      T)


(DEFENTITY-CLASS "CLASS_OF_FEATURE" :LIFECYCLE_INTEGRATION_SCHEMA NIL)

(SETF (SUBTYPE-OF (FIND-CLASS 'CLASS_OF_FEATURE))
      '(CLASS_OF_ARRANGED_INDIVIDUAL))


(DEFENTITY-CLASS "CLASS_OF_FEATURE_WHOLE_PART"
                 :LIFECYCLE_INTEGRATION_SCHEMA
  NIL)

(SETF (SUBTYPE-OF (FIND-CLASS 'CLASS_OF_FEATURE_WHOLE_PART))
      '(CLASS_OF_ARRANGEMENT_OF_INDIVIDUAL))


(DEFENTITY-CLASS "CLASS_OF_FUNCTIONAL_MAPPING"
                 :LIFECYCLE_INTEGRATION_SCHEMA
  (("codomain"
    :RANGE
    CLASS
    :SOURCE
    CLASS_OF_FUNCTIONAL_MAPPING
    :OPTIONAL
    NIL)
   ("domain"
    :RANGE
    CLASS
    :SOURCE
    CLASS_OF_FUNCTIONAL_MAPPING
    :OPTIONAL
    NIL)))

(SETF (SUBTYPE-OF (FIND-CLASS 'CLASS_OF_FUNCTIONAL_MAPPING))
      '(CLASS_OF_RELATIONSHIP))


(DEFENTITY-CLASS "CLASS_OF_FUNCTIONAL_OBJECT"
                 :LIFECYCLE_INTEGRATION_SCHEMA
  NIL)

(SETF (SUBTYPE-OF (FIND-CLASS 'CLASS_OF_FUNCTIONAL_OBJECT))
      '(CLASS_OF_ARRANGED_INDIVIDUAL))


(DEFENTITY-CLASS "CLASS_OF_IDENTIFICATION"
                 :LIFECYCLE_INTEGRATION_SCHEMA
  NIL)

(SETF (SUBTYPE-OF (FIND-CLASS 'CLASS_OF_IDENTIFICATION))
      '(CLASS_OF_REPRESENTATION_OF_THING))


(DEFENTITY-CLASS "CLASS_OF_INANIMATE_PHYSICAL_OBJECT"
                 :LIFECYCLE_INTEGRATION_SCHEMA
  NIL)

(SETF (SUBTYPE-OF (FIND-CLASS 'CLASS_OF_INANIMATE_PHYSICAL_OBJECT))
      '(CLASS_OF_ARRANGED_INDIVIDUAL))


(DEFENTITY-CLASS "CLASS_OF_INDIRECT_CONNECTION"
                 :LIFECYCLE_INTEGRATION_SCHEMA
  NIL)

(SETF (SUBTYPE-OF (FIND-CLASS 'CLASS_OF_INDIRECT_CONNECTION))
      '(CLASS_OF_CONNECTION_OF_INDIVIDUAL))


(DEFENTITY-CLASS "CLASS_OF_INDIRECT_PROPERTY"
                 :LIFECYCLE_INTEGRATION_SCHEMA
  (("class_of_possessor"
    :RANGE
    CLASS_OF_INDIVIDUAL
    :SOURCE
    CLASS_OF_INDIRECT_PROPERTY
    :OPTIONAL
    NIL)
   ("property_space"
    :RANGE
    PROPERTY_SPACE
    :SOURCE
    CLASS_OF_INDIRECT_PROPERTY
    :OPTIONAL
    NIL)))

(SETF (SUBTYPE-OF (FIND-CLASS 'CLASS_OF_INDIRECT_PROPERTY))
      '(CLASS_OF_RELATIONSHIP))


(DEFENTITY-CLASS "CLASS_OF_INDIVIDUAL" :LIFECYCLE_INTEGRATION_SCHEMA
  NIL)

(SETF (SUBTYPE-OF (FIND-CLASS 'CLASS_OF_INDIVIDUAL)) '(CLASS))


(DEFENTITY-CLASS "CLASS_OF_INDIVIDUAL_USED_IN_CONNECTION"
                 :LIFECYCLE_INTEGRATION_SCHEMA
  (("class_of_connection"
    :RANGE
    CLASS_OF_CONNECTION_OF_INDIVIDUAL
    :SOURCE
    CLASS_OF_INDIVIDUAL_USED_IN_CONNECTION
    :OPTIONAL
    NIL)
   ("class_of_usage"
    :RANGE
    CLASS_OF_INDIVIDUAL
    :SOURCE
    CLASS_OF_INDIVIDUAL_USED_IN_CONNECTION
    :OPTIONAL
    NIL)))

(SETF (SUBTYPE-OF (FIND-CLASS 'CLASS_OF_INDIVIDUAL_USED_IN_CONNECTION))
      '(CLASS_OF_RELATIONSHIP))


(DEFENTITY-CLASS "CLASS_OF_INFORMATION_OBJECT"
                 :LIFECYCLE_INTEGRATION_SCHEMA
  NIL)

(SETF (SUBTYPE-OF (FIND-CLASS 'CLASS_OF_INFORMATION_OBJECT))
      '(CLASS_OF_ARRANGED_INDIVIDUAL))


(DEFENTITY-CLASS "CLASS_OF_INFORMATION_PRESENTATION"
                 :LIFECYCLE_INTEGRATION_SCHEMA
  NIL)

(SETF (SUBTYPE-OF (FIND-CLASS 'CLASS_OF_INFORMATION_PRESENTATION))
      '(CLASS_OF_ARRANGED_INDIVIDUAL))


(DEFENTITY-CLASS "CLASS_OF_INFORMATION_REPRESENTATION"
                 :LIFECYCLE_INTEGRATION_SCHEMA
  NIL)

(SETF (SUBTYPE-OF (FIND-CLASS 'CLASS_OF_INFORMATION_REPRESENTATION))
      '(CLASS_OF_ARRANGED_INDIVIDUAL))


(DEFENTITY-CLASS "CLASS_OF_INTENDED_ROLE_AND_DOMAIN"
                 :LIFECYCLE_INTEGRATION_SCHEMA
  (("class_of_player"
    :RANGE
    CLASS_OF_INDIVIDUAL
    :SOURCE
    CLASS_OF_INTENDED_ROLE_AND_DOMAIN
    :OPTIONAL
    NIL)
   ("played"
    :RANGE
    ROLE_AND_DOMAIN
    :SOURCE
    CLASS_OF_INTENDED_ROLE_AND_DOMAIN
    :OPTIONAL
    NIL)))

(SETF (SUBTYPE-OF (FIND-CLASS 'CLASS_OF_INTENDED_ROLE_AND_DOMAIN))
      '(CLASS_OF_RELATIONSHIP))


(DEFENTITY-CLASS "CLASS_OF_INVOLVEMENT_BY_REFERENCE"
                 :LIFECYCLE_INTEGRATION_SCHEMA
  (("class_of_involved"
    :RANGE
    ROLE_AND_DOMAIN
    :SOURCE
    CLASS_OF_INVOLVEMENT_BY_REFERENCE
    :OPTIONAL
    NIL)
   ("class_of_involver"
    :RANGE
    CLASS_OF_ACTIVITY
    :SOURCE
    CLASS_OF_INVOLVEMENT_BY_REFERENCE
    :OPTIONAL
    NIL)))

(SETF (SUBTYPE-OF (FIND-CLASS 'CLASS_OF_INVOLVEMENT_BY_REFERENCE))
      '(CLASS_OF_RELATIONSHIP))


(DEFENTITY-CLASS "CLASS_OF_ISOMORPHIC_FUNCTIONAL_MAPPING"
                 :LIFECYCLE_INTEGRATION_SCHEMA
  NIL)

(SETF (SUBTYPE-OF (FIND-CLASS 'CLASS_OF_ISOMORPHIC_FUNCTIONAL_MAPPING))
      '(CLASS_OF_FUNCTIONAL_MAPPING))


(DEFENTITY-CLASS "CLASS_OF_LEFT_NAMESPACE"
                 :LIFECYCLE_INTEGRATION_SCHEMA
  NIL)

(SETF (SUBTYPE-OF (FIND-CLASS 'CLASS_OF_LEFT_NAMESPACE))
      '(CLASS_OF_NAMESPACE))


(DEFENTITY-CLASS "CLASS_OF_LIFECYCLE_STAGE"
                 :LIFECYCLE_INTEGRATION_SCHEMA
  NIL)

(SETF (SUBTYPE-OF (FIND-CLASS 'CLASS_OF_LIFECYCLE_STAGE))
      '(CLASS_OF_RELATIONSHIP))


(DEFENTITY-CLASS "CLASS_OF_MOLECULE" :LIFECYCLE_INTEGRATION_SCHEMA NIL)

(SETF (SUBTYPE-OF (FIND-CLASS 'CLASS_OF_MOLECULE))
      '(CLASS_OF_ARRANGED_INDIVIDUAL))


(DEFENTITY-CLASS "CLASS_OF_MULTIDIMENSIONAL_OBJECT"
                 :LIFECYCLE_INTEGRATION_SCHEMA
  (("cardinalities"
    :RANGE
    (MAKE-INSTANCE 'LIST-TYP
                   :L-BOUND
                   1
                   :U-BOUND
                   :?
                   :BASE-TYPE
                   'CARDINALITY
                   :UNIQUE
                   NIL)
    :SOURCE
    CLASS_OF_MULTIDIMENSIONAL_OBJECT
    :OPTIONAL
    T)
   ("optional_element"
    :RANGE
    (MAKE-INSTANCE 'LIST-TYP
                   :L-BOUND
                   1
                   :U-BOUND
                   :?
                   :BASE-TYPE
                   (MAKE-INSTANCE 'BOOLEAN-TYP)
                   :UNIQUE
                   NIL)
    :SOURCE
    CLASS_OF_MULTIDIMENSIONAL_OBJECT
    :OPTIONAL
    NIL)
   ("parameters"
    :RANGE
    (MAKE-INSTANCE 'LIST-TYP
                   :L-BOUND
                   1
                   :U-BOUND
                   :?
                   :BASE-TYPE
                   'THING
                   :UNIQUE
                   NIL)
    :SOURCE
    CLASS_OF_MULTIDIMENSIONAL_OBJECT
    :OPTIONAL
    T)
   ("parameter_position"
    :RANGE
    (MAKE-INSTANCE 'LIST-TYP
                   :L-BOUND
                   1
                   :U-BOUND
                   :?
                   :BASE-TYPE
                   (MAKE-INSTANCE 'INTEGER-TYP)
                   :UNIQUE
                   NIL)
    :SOURCE
    CLASS_OF_MULTIDIMENSIONAL_OBJECT
    :OPTIONAL
    T)
   ("roles"
    :RANGE
    (MAKE-INSTANCE 'LIST-TYP
                   :L-BOUND
                   1
                   :U-BOUND
                   :?
                   :BASE-TYPE
                   'ROLE_AND_DOMAIN
                   :UNIQUE
                   NIL)
    :SOURCE
    CLASS_OF_MULTIDIMENSIONAL_OBJECT
    :OPTIONAL
    NIL)))

(SETF (SUBTYPE-OF (FIND-CLASS 'CLASS_OF_MULTIDIMENSIONAL_OBJECT))
      '(CLASS_OF_ABSTRACT_OBJECT))


(DEFENTITY-CLASS "CLASS_OF_NAMESPACE" :LIFECYCLE_INTEGRATION_SCHEMA
  (("class_of_class_of_whole"
    :RANGE
    CLASS_OF_CLASS_OF_INFORMATION_REPRESENTATION
    :SOURCE
    CLASS_OF_NAMESPACE
    :OPTIONAL
    NIL)
   ("class_of_part"
    :RANGE
    CLASS_OF_INFORMATION_REPRESENTATION
    :SOURCE
    CLASS_OF_NAMESPACE
    :OPTIONAL
    NIL)))

(SETF (SUBTYPE-OF (FIND-CLASS 'CLASS_OF_NAMESPACE))
      '(CLASS_OF_CLASS_OF_RELATIONSHIP))


(DEFENTITY-CLASS "CLASS_OF_NUMBER" :LIFECYCLE_INTEGRATION_SCHEMA NIL)

(SETF (SUBTYPE-OF (FIND-CLASS 'CLASS_OF_NUMBER)) '(CLASS_OF_CLASS))


(DEFENTITY-CLASS "CLASS_OF_ORGANISM" :LIFECYCLE_INTEGRATION_SCHEMA NIL)

(SETF (SUBTYPE-OF (FIND-CLASS 'CLASS_OF_ORGANISM))
      '(CLASS_OF_ARRANGED_INDIVIDUAL))


(DEFENTITY-CLASS "CLASS_OF_ORGANIZATION" :LIFECYCLE_INTEGRATION_SCHEMA
  NIL)

(SETF (SUBTYPE-OF (FIND-CLASS 'CLASS_OF_ORGANIZATION))
      '(CLASS_OF_ARRANGED_INDIVIDUAL))


(DEFENTITY-CLASS "CLASS_OF_PARTICIPATION" :LIFECYCLE_INTEGRATION_SCHEMA
  (("class_of_part"
    :RANGE
    PARTICIPATING_ROLE_AND_DOMAIN
    :SOURCE
    CLASS_OF_COMPOSITION_OF_INDIVIDUAL
    :REDEFINITION-OF
    (CLASS_OF_COMPOSITION_OF_INDIVIDUAL "class_of_part")
    :OPTIONAL
    NIL)
   ("class_of_whole"
    :RANGE
    CLASS_OF_ACTIVITY
    :SOURCE
    CLASS_OF_COMPOSITION_OF_INDIVIDUAL
    :REDEFINITION-OF
    (CLASS_OF_COMPOSITION_OF_INDIVIDUAL "class_of_whole")
    :OPTIONAL
    NIL)))

(SETF (SUBTYPE-OF (FIND-CLASS 'CLASS_OF_PARTICIPATION))
      '(CLASS_OF_COMPOSITION_OF_INDIVIDUAL))


(DEFENTITY-CLASS "CLASS_OF_PARTICULATE_MATERIAL"
                 :LIFECYCLE_INTEGRATION_SCHEMA
  NIL)

(SETF (SUBTYPE-OF (FIND-CLASS 'CLASS_OF_PARTICULATE_MATERIAL))
      '(CLASS_OF_ARRANGED_INDIVIDUAL))


(DEFENTITY-CLASS "CLASS_OF_PERIOD_IN_TIME"
                 :LIFECYCLE_INTEGRATION_SCHEMA
  NIL)

(SETF (SUBTYPE-OF (FIND-CLASS 'CLASS_OF_PERIOD_IN_TIME))
      '(CLASS_OF_INDIVIDUAL))


(DEFENTITY-CLASS "CLASS_OF_PERSON" :LIFECYCLE_INTEGRATION_SCHEMA NIL)

(SETF (SUBTYPE-OF (FIND-CLASS 'CLASS_OF_PERSON)) '(CLASS_OF_ORGANISM))


(DEFENTITY-CLASS "CLASS_OF_POINT_IN_TIME" :LIFECYCLE_INTEGRATION_SCHEMA
  NIL)

(SETF (SUBTYPE-OF (FIND-CLASS 'CLASS_OF_POINT_IN_TIME))
      '(CLASS_OF_EVENT))


(DEFENTITY-CLASS "CLASS_OF_POSSIBLE_ROLE_AND_DOMAIN"
                 :LIFECYCLE_INTEGRATION_SCHEMA
  (("class_of_player"
    :RANGE
    CLASS_OF_INDIVIDUAL
    :SOURCE
    CLASS_OF_POSSIBLE_ROLE_AND_DOMAIN
    :OPTIONAL
    NIL)
   ("played"
    :RANGE
    ROLE_AND_DOMAIN
    :SOURCE
    CLASS_OF_POSSIBLE_ROLE_AND_DOMAIN
    :OPTIONAL
    NIL)))

(SETF (SUBTYPE-OF (FIND-CLASS 'CLASS_OF_POSSIBLE_ROLE_AND_DOMAIN))
      '(CLASS_OF_RELATIONSHIP))


(DEFENTITY-CLASS "CLASS_OF_PROPERTY" :LIFECYCLE_INTEGRATION_SCHEMA NIL)

(SETF (SUBTYPE-OF (FIND-CLASS 'CLASS_OF_PROPERTY))
      '(CLASS_OF_CLASS_OF_INDIVIDUAL))


(DEFENTITY-CLASS "CLASS_OF_PROPERTY_SPACE"
                 :LIFECYCLE_INTEGRATION_SCHEMA
  NIL)

(SETF (SUBTYPE-OF (FIND-CLASS 'CLASS_OF_PROPERTY_SPACE))
      '(CLASS_OF_CLASS))


(DEFENTITY-CLASS "CLASS_OF_RECOGNITION" :LIFECYCLE_INTEGRATION_SCHEMA
  (("class_of_recognized"
    :RANGE
    CLASS
    :SOURCE
    CLASS_OF_RECOGNITION
    :OPTIONAL
    NIL)
   ("class_of_recognizing"
    :RANGE
    CLASS_OF_ACTIVITY
    :SOURCE
    CLASS_OF_RECOGNITION
    :OPTIONAL
    NIL)))

(SETF (SUBTYPE-OF (FIND-CLASS 'CLASS_OF_RECOGNITION))
      '(CLASS_OF_RELATIONSHIP))


(DEFENTITY-CLASS "CLASS_OF_RELATIONSHIP" :LIFECYCLE_INTEGRATION_SCHEMA
  (("end_1_cardinality"
    :RANGE
    CARDINALITY
    :SOURCE
    CLASS_OF_RELATIONSHIP
    :OPTIONAL
    T)
   ("end_2_cardinality"
    :RANGE
    CARDINALITY
    :SOURCE
    CLASS_OF_RELATIONSHIP
    :OPTIONAL
    T)))

(SETF (SUBTYPE-OF (FIND-CLASS 'CLASS_OF_RELATIONSHIP))
      '(CLASS_OF_ABSTRACT_OBJECT))


(DEFENTITY-CLASS "CLASS_OF_RELATIONSHIP_WITH_RELATED_END_1"
                 :LIFECYCLE_INTEGRATION_SCHEMA
  (("related"
    :RANGE
    THING
    :SOURCE
    CLASS_OF_RELATIONSHIP_WITH_RELATED_END_1
    :OPTIONAL
    NIL)))

(SETF (SUBTYPE-OF (FIND-CLASS 'CLASS_OF_RELATIONSHIP_WITH_RELATED_END_1))
      '(CLASS_OF_RELATIONSHIP))


(DEFENTITY-CLASS "CLASS_OF_RELATIONSHIP_WITH_RELATED_END_2"
                 :LIFECYCLE_INTEGRATION_SCHEMA
  (("related"
    :RANGE
    THING
    :SOURCE
    CLASS_OF_RELATIONSHIP_WITH_RELATED_END_2
    :OPTIONAL
    NIL)))

(SETF (SUBTYPE-OF (FIND-CLASS 'CLASS_OF_RELATIONSHIP_WITH_RELATED_END_2))
      '(CLASS_OF_RELATIONSHIP))


(DEFENTITY-CLASS "CLASS_OF_RELATIONSHIP_WITH_SIGNATURE"
                 :LIFECYCLE_INTEGRATION_SCHEMA
  (("class_of_end_1"
    :RANGE
    ROLE_AND_DOMAIN
    :SOURCE
    CLASS_OF_RELATIONSHIP_WITH_SIGNATURE
    :OPTIONAL
    T)
   ("class_of_end_2"
    :RANGE
    ROLE_AND_DOMAIN
    :SOURCE
    CLASS_OF_RELATIONSHIP_WITH_SIGNATURE
    :OPTIONAL
    T)))

(SETF (SUBTYPE-OF (FIND-CLASS 'CLASS_OF_RELATIONSHIP_WITH_SIGNATURE))
      '(CLASS_OF_RELATIONSHIP RELATIONSHIP))


(DEFENTITY-CLASS "CLASS_OF_RELATIVE_LOCATION"
                 :LIFECYCLE_INTEGRATION_SCHEMA
  (("class_of_located"
    :RANGE
    CLASS_OF_INDIVIDUAL
    :SOURCE
    CLASS_OF_RELATIVE_LOCATION
    :OPTIONAL
    NIL)
   ("class_of_locator"
    :RANGE
    CLASS_OF_INDIVIDUAL
    :SOURCE
    CLASS_OF_RELATIVE_LOCATION
    :OPTIONAL
    NIL)))

(SETF (SUBTYPE-OF (FIND-CLASS 'CLASS_OF_RELATIVE_LOCATION))
      '(CLASS_OF_RELATIONSHIP))


(DEFENTITY-CLASS "CLASS_OF_REPRESENTATION_OF_THING"
                 :LIFECYCLE_INTEGRATION_SCHEMA
  (("pattern"
    :RANGE
    CLASS_OF_INFORMATION_REPRESENTATION
    :SOURCE
    CLASS_OF_REPRESENTATION_OF_THING
    :OPTIONAL
    NIL)
   ("represented"
    :RANGE
    THING
    :SOURCE
    CLASS_OF_REPRESENTATION_OF_THING
    :OPTIONAL
    NIL)))

(SETF (SUBTYPE-OF (FIND-CLASS 'CLASS_OF_REPRESENTATION_OF_THING))
      '(CLASS_OF_RELATIONSHIP))


(DEFENTITY-CLASS "CLASS_OF_REPRESENTATION_TRANSLATION"
                 :LIFECYCLE_INTEGRATION_SCHEMA
  (("class_of_first"
    :RANGE
    CLASS_OF_INFORMATION_REPRESENTATION
    :SOURCE
    CLASS_OF_REPRESENTATION_TRANSLATION
    :OPTIONAL
    NIL)
   ("class_of_second"
    :RANGE
    CLASS_OF_INFORMATION_REPRESENTATION
    :SOURCE
    CLASS_OF_REPRESENTATION_TRANSLATION
    :OPTIONAL
    NIL)))

(SETF (SUBTYPE-OF (FIND-CLASS 'CLASS_OF_REPRESENTATION_TRANSLATION))
      '(CLASS_OF_RELATIONSHIP))


(DEFENTITY-CLASS "CLASS_OF_RESPONSIBILITY_FOR_REPRESENTATION"
                 :LIFECYCLE_INTEGRATION_SCHEMA
  (("class_of_controlled"
    :RANGE
    CLASS_OF_REPRESENTATION_OF_THING
    :SOURCE
    CLASS_OF_RESPONSIBILITY_FOR_REPRESENTATION
    :OPTIONAL
    NIL)
   ("controller"
    :RANGE
    POSSIBLE_INDIVIDUAL
    :SOURCE
    CLASS_OF_RESPONSIBILITY_FOR_REPRESENTATION
    :OPTIONAL
    NIL)))

(SETF (SUBTYPE-OF (FIND-CLASS 'CLASS_OF_RESPONSIBILITY_FOR_REPRESENTATION))
      '(CLASS_OF_RELATIONSHIP))


(DEFENTITY-CLASS "CLASS_OF_RIGHT_NAMESPACE"
                 :LIFECYCLE_INTEGRATION_SCHEMA
  NIL)

(SETF (SUBTYPE-OF (FIND-CLASS 'CLASS_OF_RIGHT_NAMESPACE))
      '(CLASS_OF_NAMESPACE))


(DEFENTITY-CLASS "CLASS_OF_SCALE" :LIFECYCLE_INTEGRATION_SCHEMA NIL)

(SETF (SUBTYPE-OF (FIND-CLASS 'CLASS_OF_SCALE))
      '(CLASS_OF_CLASS_OF_RELATIONSHIP))


(DEFENTITY-CLASS "CLASS_OF_SCALE_CONVERSION"
                 :LIFECYCLE_INTEGRATION_SCHEMA
  (("codomain"
    :RANGE
    SCALE
    :SOURCE
    CLASS_OF_FUNCTIONAL_MAPPING
    :REDEFINITION-OF
    (CLASS_OF_FUNCTIONAL_MAPPING "codomain")
    :OPTIONAL
    NIL)
   ("domain"
    :RANGE
    SCALE
    :SOURCE
    CLASS_OF_FUNCTIONAL_MAPPING
    :REDEFINITION-OF
    (CLASS_OF_FUNCTIONAL_MAPPING "domain")
    :OPTIONAL
    NIL)))

(SETF (SUBTYPE-OF (FIND-CLASS 'CLASS_OF_SCALE_CONVERSION))
      '(CLASS_OF_ISOMORPHIC_FUNCTIONAL_MAPPING))


(DEFENTITY-CLASS "CLASS_OF_SHAPE" :LIFECYCLE_INTEGRATION_SCHEMA NIL)

(SETF (SUBTYPE-OF (FIND-CLASS 'CLASS_OF_SHAPE)) '(PROPERTY_SPACE))


(DEFENTITY-CLASS "CLASS_OF_SHAPE_DIMENSION"
                 :LIFECYCLE_INTEGRATION_SCHEMA
  NIL)

(SETF (SUBTYPE-OF (FIND-CLASS 'CLASS_OF_SHAPE_DIMENSION))
      '(CLASS_OF_CLASS))


(DEFENTITY-CLASS "CLASS_OF_SPECIALIZATION"
                 :LIFECYCLE_INTEGRATION_SCHEMA
  (("class_of_subclass"
    :RANGE
    CLASS_OF_CLASS
    :SOURCE
    CLASS_OF_SPECIALIZATION
    :OPTIONAL
    NIL)
   ("class_of_superclass"
    :RANGE
    CLASS_OF_CLASS
    :SOURCE
    CLASS_OF_SPECIALIZATION
    :OPTIONAL
    NIL)))

(SETF (SUBTYPE-OF (FIND-CLASS 'CLASS_OF_SPECIALIZATION))
      '(CLASS_OF_RELATIONSHIP))


(DEFENTITY-CLASS "CLASS_OF_STATUS" :LIFECYCLE_INTEGRATION_SCHEMA NIL)

(SETF (SUBTYPE-OF (FIND-CLASS 'CLASS_OF_STATUS))
      '(CLASS_OF_CLASS_OF_INDIVIDUAL))


(DEFENTITY-CLASS "CLASS_OF_SUB_ATOMIC_PARTICLE"
                 :LIFECYCLE_INTEGRATION_SCHEMA
  NIL)

(SETF (SUBTYPE-OF (FIND-CLASS 'CLASS_OF_SUB_ATOMIC_PARTICLE))
      '(CLASS_OF_ARRANGED_INDIVIDUAL))


(DEFENTITY-CLASS "CLASS_OF_TEMPORAL_SEQUENCE"
                 :LIFECYCLE_INTEGRATION_SCHEMA
  (("class_of_predecessor"
    :RANGE
    CLASS_OF_INDIVIDUAL
    :SOURCE
    CLASS_OF_TEMPORAL_SEQUENCE
    :OPTIONAL
    NIL)
   ("class_of_successor"
    :RANGE
    CLASS_OF_INDIVIDUAL
    :SOURCE
    CLASS_OF_TEMPORAL_SEQUENCE
    :OPTIONAL
    NIL)))

(SETF (SUBTYPE-OF (FIND-CLASS 'CLASS_OF_TEMPORAL_SEQUENCE))
      '(CLASS_OF_RELATIONSHIP))


(DEFENTITY-CLASS "CLASS_OF_TEMPORAL_WHOLE_PART"
                 :LIFECYCLE_INTEGRATION_SCHEMA
  NIL)

(SETF (SUBTYPE-OF (FIND-CLASS 'CLASS_OF_TEMPORAL_WHOLE_PART))
      '(CLASS_OF_COMPOSITION_OF_INDIVIDUAL))


(DEFENTITY-CLASS "CLASS_OF_USAGE_OF_REPRESENTATION"
                 :LIFECYCLE_INTEGRATION_SCHEMA
  (("class_of_used"
    :RANGE
    CLASS_OF_REPRESENTATION_OF_THING
    :SOURCE
    CLASS_OF_USAGE_OF_REPRESENTATION
    :OPTIONAL
    NIL)
   ("user"
    :RANGE
    POSSIBLE_INDIVIDUAL
    :SOURCE
    CLASS_OF_USAGE_OF_REPRESENTATION
    :OPTIONAL
    NIL)))

(SETF (SUBTYPE-OF (FIND-CLASS 'CLASS_OF_USAGE_OF_REPRESENTATION))
      '(CLASS_OF_RELATIONSHIP))


(DEFENTITY-CLASS "CLASSIFICATION" :LIFECYCLE_INTEGRATION_SCHEMA
  (("classified" :RANGE THING :SOURCE CLASSIFICATION :OPTIONAL NIL)
   ("classifier" :RANGE CLASS :SOURCE CLASSIFICATION :OPTIONAL NIL)))

(SETF (SUBTYPE-OF (FIND-CLASS 'CLASSIFICATION)) '(RELATIONSHIP))


(DEFENTITY-CLASS "COMPARISON_OF_PROPERTY" :LIFECYCLE_INTEGRATION_SCHEMA
  (("greater_element"
    :RANGE
    PROPERTY
    :SOURCE
    COMPARISON_OF_PROPERTY
    :OPTIONAL
    NIL)
   ("lesser_element"
    :RANGE
    PROPERTY
    :SOURCE
    COMPARISON_OF_PROPERTY
    :OPTIONAL
    NIL)))

(SETF (SUBTYPE-OF (FIND-CLASS 'COMPARISON_OF_PROPERTY)) '(RELATIONSHIP))


(DEFENTITY-CLASS "COMPOSITION_OF_INDIVIDUAL"
                 :LIFECYCLE_INTEGRATION_SCHEMA
  (("part"
    :RANGE
    POSSIBLE_INDIVIDUAL
    :SOURCE
    COMPOSITION_OF_INDIVIDUAL
    :OPTIONAL
    NIL)
   ("whole"
    :RANGE
    POSSIBLE_INDIVIDUAL
    :SOURCE
    COMPOSITION_OF_INDIVIDUAL
    :OPTIONAL
    NIL)))

(SETF (SUBTYPE-OF (FIND-CLASS 'COMPOSITION_OF_INDIVIDUAL))
      '(RELATIONSHIP))


(DEFENTITY-CLASS "CONNECTION_OF_INDIVIDUAL"
                 :LIFECYCLE_INTEGRATION_SCHEMA
  (("side_1"
    :RANGE
    POSSIBLE_INDIVIDUAL
    :SOURCE
    CONNECTION_OF_INDIVIDUAL
    :OPTIONAL
    NIL)
   ("side_2"
    :RANGE
    POSSIBLE_INDIVIDUAL
    :SOURCE
    CONNECTION_OF_INDIVIDUAL
    :OPTIONAL
    NIL)))

(SETF (SUBTYPE-OF (FIND-CLASS 'CONNECTION_OF_INDIVIDUAL))
      '(RELATIONSHIP))


(DEFENTITY-CLASS "CONTAINMENT_OF_INDIVIDUAL"
                 :LIFECYCLE_INTEGRATION_SCHEMA
  NIL)

(SETF (SUBTYPE-OF (FIND-CLASS 'CONTAINMENT_OF_INDIVIDUAL))
      '(RELATIVE_LOCATION))


(DEFENTITY-CLASS "COORDINATE_SYSTEM" :LIFECYCLE_INTEGRATION_SCHEMA NIL)

(SETF (SUBTYPE-OF (FIND-CLASS 'COORDINATE_SYSTEM))
      '(MULTIDIMENSIONAL_SCALE))


(DEFENTITY-CLASS "CRYSTALLINE_STRUCTURE" :LIFECYCLE_INTEGRATION_SCHEMA
  NIL)

(SETF (SUBTYPE-OF (FIND-CLASS 'CRYSTALLINE_STRUCTURE))
      '(CLASS_OF_ARRANGED_INDIVIDUAL))


(DEFENTITY-CLASS "DEFINITION" :LIFECYCLE_INTEGRATION_SCHEMA
  (("represented"
    :RANGE
    CLASS
    :SOURCE
    REPRESENTATION_OF_THING
    :REDEFINITION-OF
    (REPRESENTATION_OF_THING "represented")
    :OPTIONAL
    NIL)))

(SETF (SUBTYPE-OF (FIND-CLASS 'DEFINITION)) '(REPRESENTATION_OF_THING))


(DEFENTITY-CLASS "DESCRIPTION" :LIFECYCLE_INTEGRATION_SCHEMA NIL)

(SETF (SUBTYPE-OF (FIND-CLASS 'DESCRIPTION)) '(REPRESENTATION_OF_THING))


(DEFENTITY-CLASS "DIFFERENCE_OF_SET_OF_CLASS"
                 :LIFECYCLE_INTEGRATION_SCHEMA
  (("input"
    :RANGE
    ENUMERATED_SET_OF_CLASS
    :SOURCE
    FUNCTIONAL_MAPPING
    :REDEFINITION-OF
    (FUNCTIONAL_MAPPING "input")
    :OPTIONAL
    NIL)
   ("result"
    :RANGE
    CLASS
    :SOURCE
    FUNCTIONAL_MAPPING
    :REDEFINITION-OF
    (FUNCTIONAL_MAPPING "result")
    :OPTIONAL
    NIL)))

(SETF (SUBTYPE-OF (FIND-CLASS 'DIFFERENCE_OF_SET_OF_CLASS))
      '(FUNCTIONAL_MAPPING))


(DEFENTITY-CLASS "DIMENSION_OF_INDIVIDUAL"
                 :LIFECYCLE_INTEGRATION_SCHEMA
  (("individual"
    :RANGE
    POSSIBLE_INDIVIDUAL
    :SOURCE
    DIMENSION_OF_INDIVIDUAL
    :OPTIONAL
    NIL)
   ("individual_dimension"
    :RANGE
    INDIVIDUAL_DIMENSION
    :SOURCE
    DIMENSION_OF_INDIVIDUAL
    :OPTIONAL
    NIL)))

(SETF (SUBTYPE-OF (FIND-CLASS 'DIMENSION_OF_INDIVIDUAL))
      '(CLASS_OF_RELATIONSHIP))


(DEFENTITY-CLASS "DIMENSION_OF_SHAPE" :LIFECYCLE_INTEGRATION_SCHEMA
  (("dimension"
    :RANGE
    SHAPE_DIMENSION
    :SOURCE
    DIMENSION_OF_SHAPE
    :OPTIONAL
    NIL)
   ("shape" :RANGE SHAPE :SOURCE DIMENSION_OF_SHAPE :OPTIONAL NIL)))

(SETF (SUBTYPE-OF (FIND-CLASS 'DIMENSION_OF_SHAPE))
      '(CLASS_OF_CLASS_OF_RELATIONSHIP))


(DEFENTITY-CLASS "DIRECT_CONNECTION" :LIFECYCLE_INTEGRATION_SCHEMA NIL)

(SETF (SUBTYPE-OF (FIND-CLASS 'DIRECT_CONNECTION))
      '(CONNECTION_OF_INDIVIDUAL))


(DEFENTITY-CLASS "DOCUMENT_DEFINITION" :LIFECYCLE_INTEGRATION_SCHEMA
  NIL)

(SETF (SUBTYPE-OF (FIND-CLASS 'DOCUMENT_DEFINITION))
      '(CLASS_OF_CLASS_OF_INFORMATION_REPRESENTATION))


(DEFENTITY-CLASS "ENDING" :LIFECYCLE_INTEGRATION_SCHEMA NIL)

(SETF (SUBTYPE-OF (FIND-CLASS 'ENDING)) '(TEMPORAL_BOUNDING))


(DEFENTITY-CLASS "ENUMERATED_NUMBER_SET" :LIFECYCLE_INTEGRATION_SCHEMA
  NIL)

(SETF (SUBTYPE-OF (FIND-CLASS 'ENUMERATED_NUMBER_SET))
      '(CLASS_OF_NUMBER ENUMERATED_SET_OF_CLASS))


(DEFENTITY-CLASS "ENUMERATED_PROPERTY_SET"
                 :LIFECYCLE_INTEGRATION_SCHEMA
  NIL)

(SETF (SUBTYPE-OF (FIND-CLASS 'ENUMERATED_PROPERTY_SET))
      '(CLASS_OF_PROPERTY ENUMERATED_SET_OF_CLASS))


(DEFENTITY-CLASS "ENUMERATED_SET_OF_CLASS"
                 :LIFECYCLE_INTEGRATION_SCHEMA
  NIL)

(SETF (SUBTYPE-OF (FIND-CLASS 'ENUMERATED_SET_OF_CLASS))
      '(CLASS_OF_CLASS))


(DEFENTITY-CLASS "EVENT" :LIFECYCLE_INTEGRATION_SCHEMA NIL)

(SETF (SUBTYPE-OF (FIND-CLASS 'EVENT)) '(POSSIBLE_INDIVIDUAL))


(DEFENTITY-CLASS "EXPRESS_BINARY" :LIFECYCLE_INTEGRATION_SCHEMA
  (("content"
    :RANGE
    (MAKE-INSTANCE 'BINARY-TYP)
    :SOURCE
    EXPRESS_BINARY
    :OPTIONAL
    NIL)))

(SETF (SUBTYPE-OF (FIND-CLASS 'EXPRESS_BINARY))
      '(CLASS_OF_EXPRESS_INFORMATION_REPRESENTATION))


(DEFENTITY-CLASS "EXPRESS_BOOLEAN" :LIFECYCLE_INTEGRATION_SCHEMA
  (("content"
    :RANGE
    (MAKE-INSTANCE 'BOOLEAN-TYP)
    :SOURCE
    EXPRESS_BOOLEAN
    :OPTIONAL
    NIL)))

(SETF (SUBTYPE-OF (FIND-CLASS 'EXPRESS_BOOLEAN))
      '(CLASS_OF_EXPRESS_INFORMATION_REPRESENTATION))


(DEFENTITY-CLASS "EXPRESS_INTEGER" :LIFECYCLE_INTEGRATION_SCHEMA
  (("content"
    :RANGE
    (MAKE-INSTANCE 'INTEGER-TYP)
    :SOURCE
    EXPRESS_INTEGER
    :OPTIONAL
    NIL)))

(SETF (SUBTYPE-OF (FIND-CLASS 'EXPRESS_INTEGER))
      '(CLASS_OF_EXPRESS_INFORMATION_REPRESENTATION))


(DEFENTITY-CLASS "EXPRESS_LOGICAL" :LIFECYCLE_INTEGRATION_SCHEMA
  (("content"
    :RANGE
    (MAKE-INSTANCE 'LOGICAL-TYP)
    :SOURCE
    EXPRESS_LOGICAL
    :OPTIONAL
    NIL)))

(SETF (SUBTYPE-OF (FIND-CLASS 'EXPRESS_LOGICAL))
      '(CLASS_OF_EXPRESS_INFORMATION_REPRESENTATION))


(DEFENTITY-CLASS "EXPRESS_REAL" :LIFECYCLE_INTEGRATION_SCHEMA
  (("content"
    :RANGE
    (MAKE-INSTANCE 'REAL-TYP)
    :SOURCE
    EXPRESS_REAL
    :OPTIONAL
    NIL)))

(SETF (SUBTYPE-OF (FIND-CLASS 'EXPRESS_REAL))
      '(CLASS_OF_EXPRESS_INFORMATION_REPRESENTATION))


(DEFENTITY-CLASS "EXPRESS_STRING" :LIFECYCLE_INTEGRATION_SCHEMA
  (("content"
    :RANGE
    (MAKE-INSTANCE 'STRING-TYP)
    :SOURCE
    EXPRESS_STRING
    :OPTIONAL
    NIL)))

(SETF (SUBTYPE-OF (FIND-CLASS 'EXPRESS_STRING))
      '(CLASS_OF_EXPRESS_INFORMATION_REPRESENTATION))


(DEFENTITY-CLASS "FEATURE_WHOLE_PART" :LIFECYCLE_INTEGRATION_SCHEMA NIL)

(SETF (SUBTYPE-OF (FIND-CLASS 'FEATURE_WHOLE_PART))
      '(ARRANGEMENT_OF_INDIVIDUAL))


(DEFENTITY-CLASS "FUNCTIONAL_MAPPING" :LIFECYCLE_INTEGRATION_SCHEMA
  (("input" :RANGE THING :SOURCE FUNCTIONAL_MAPPING :OPTIONAL NIL)
   ("result" :RANGE THING :SOURCE FUNCTIONAL_MAPPING :OPTIONAL NIL)))

(SETF (SUBTYPE-OF (FIND-CLASS 'FUNCTIONAL_MAPPING)) '(RELATIONSHIP))


(DEFENTITY-CLASS "FUNCTIONAL_PHYSICAL_OBJECT"
                 :LIFECYCLE_INTEGRATION_SCHEMA
  NIL)

(SETF (SUBTYPE-OF (FIND-CLASS 'FUNCTIONAL_PHYSICAL_OBJECT))
      '(PHYSICAL_OBJECT))


(DEFENTITY-CLASS "IDENTIFICATION" :LIFECYCLE_INTEGRATION_SCHEMA NIL)

(SETF (SUBTYPE-OF (FIND-CLASS 'IDENTIFICATION))
      '(REPRESENTATION_OF_THING))


(DEFENTITY-CLASS "INDIRECT_CONNECTION" :LIFECYCLE_INTEGRATION_SCHEMA
  NIL)

(SETF (SUBTYPE-OF (FIND-CLASS 'INDIRECT_CONNECTION))
      '(CONNECTION_OF_INDIVIDUAL))


(DEFENTITY-CLASS "INDIRECT_PROPERTY" :LIFECYCLE_INTEGRATION_SCHEMA
  (("possessor"
    :RANGE
    POSSIBLE_INDIVIDUAL
    :SOURCE
    INDIRECT_PROPERTY
    :OPTIONAL
    NIL)
   ("property"
    :RANGE
    PROPERTY
    :SOURCE
    INDIRECT_PROPERTY
    :OPTIONAL
    NIL)))

(SETF (SUBTYPE-OF (FIND-CLASS 'INDIRECT_PROPERTY)) '(RELATIONSHIP))


(DEFENTITY-CLASS "INDIVIDUAL_DIMENSION" :LIFECYCLE_INTEGRATION_SCHEMA
  NIL)

(SETF (SUBTYPE-OF (FIND-CLASS 'INDIVIDUAL_DIMENSION))
      '(CLASS_OF_INDIVIDUAL))


(DEFENTITY-CLASS "INDIVIDUAL_USED_IN_CONNECTION"
                 :LIFECYCLE_INTEGRATION_SCHEMA
  (("connection"
    :RANGE
    CONNECTION_OF_INDIVIDUAL
    :SOURCE
    INDIVIDUAL_USED_IN_CONNECTION
    :OPTIONAL
    NIL)
   ("usage"
    :RANGE
    POSSIBLE_INDIVIDUAL
    :SOURCE
    INDIVIDUAL_USED_IN_CONNECTION
    :OPTIONAL
    NIL)))

(SETF (SUBTYPE-OF (FIND-CLASS 'INDIVIDUAL_USED_IN_CONNECTION))
      '(RELATIONSHIP))


(DEFENTITY-CLASS "INTEGER_NUMBER" :LIFECYCLE_INTEGRATION_SCHEMA NIL)

(SETF (SUBTYPE-OF (FIND-CLASS 'INTEGER_NUMBER)) '(ARITHMETIC_NUMBER))


(DEFENTITY-CLASS "INTENDED_ROLE_AND_DOMAIN"
                 :LIFECYCLE_INTEGRATION_SCHEMA
  (("played"
    :RANGE
    ROLE_AND_DOMAIN
    :SOURCE
    INTENDED_ROLE_AND_DOMAIN
    :OPTIONAL
    NIL)
   ("player"
    :RANGE
    POSSIBLE_INDIVIDUAL
    :SOURCE
    INTENDED_ROLE_AND_DOMAIN
    :OPTIONAL
    NIL)))

(SETF (SUBTYPE-OF (FIND-CLASS 'INTENDED_ROLE_AND_DOMAIN))
      '(RELATIONSHIP))


(DEFENTITY-CLASS "INTERSECTION_OF_SET_OF_CLASS"
                 :LIFECYCLE_INTEGRATION_SCHEMA
  (("input"
    :RANGE
    ENUMERATED_SET_OF_CLASS
    :SOURCE
    FUNCTIONAL_MAPPING
    :REDEFINITION-OF
    (FUNCTIONAL_MAPPING "input")
    :OPTIONAL
    NIL)
   ("result"
    :RANGE
    CLASS
    :SOURCE
    FUNCTIONAL_MAPPING
    :REDEFINITION-OF
    (FUNCTIONAL_MAPPING "result")
    :OPTIONAL
    NIL)))

(SETF (SUBTYPE-OF (FIND-CLASS 'INTERSECTION_OF_SET_OF_CLASS))
      '(FUNCTIONAL_MAPPING))


(DEFENTITY-CLASS "INVOLVEMENT_BY_REFERENCE"
                 :LIFECYCLE_INTEGRATION_SCHEMA
  (("involved"
    :RANGE
    THING
    :SOURCE
    INVOLVEMENT_BY_REFERENCE
    :OPTIONAL
    NIL)
   ("involver"
    :RANGE
    ACTIVITY
    :SOURCE
    INVOLVEMENT_BY_REFERENCE
    :OPTIONAL
    NIL)))

(SETF (SUBTYPE-OF (FIND-CLASS 'INVOLVEMENT_BY_REFERENCE))
      '(RELATIONSHIP))


(DEFENTITY-CLASS "LANGUAGE" :LIFECYCLE_INTEGRATION_SCHEMA NIL)

(SETF (SUBTYPE-OF (FIND-CLASS 'LANGUAGE))
      '(CLASS_OF_CLASS_OF_INFORMATION_REPRESENTATION))


(DEFENTITY-CLASS "LEFT_NAMESPACE" :LIFECYCLE_INTEGRATION_SCHEMA NIL)

(SETF (SUBTYPE-OF (FIND-CLASS 'LEFT_NAMESPACE)) '(NAMESPACE))


(DEFENTITY-CLASS "LIFECYCLE_STAGE" :LIFECYCLE_INTEGRATION_SCHEMA
  (("interest"
    :RANGE
    POSSIBLE_INDIVIDUAL
    :SOURCE
    LIFECYCLE_STAGE
    :OPTIONAL
    NIL)
   ("interested"
    :RANGE
    POSSIBLE_INDIVIDUAL
    :SOURCE
    LIFECYCLE_STAGE
    :OPTIONAL
    NIL)))

(SETF (SUBTYPE-OF (FIND-CLASS 'LIFECYCLE_STAGE)) '(RELATIONSHIP))


(DEFENTITY-CLASS "LOWER_BOUND_OF_NUMBER_RANGE"
                 :LIFECYCLE_INTEGRATION_SCHEMA
  (("classified"
    :RANGE
    ARITHMETIC_NUMBER
    :SOURCE
    CLASSIFICATION
    :REDEFINITION-OF
    (CLASSIFICATION "classified")
    :OPTIONAL
    NIL)
   ("classifier"
    :RANGE
    NUMBER_RANGE
    :SOURCE
    CLASSIFICATION
    :REDEFINITION-OF
    (CLASSIFICATION "classifier")
    :OPTIONAL
    NIL)))

(SETF (SUBTYPE-OF (FIND-CLASS 'LOWER_BOUND_OF_NUMBER_RANGE))
      '(CLASSIFICATION))


(DEFENTITY-CLASS "LOWER_BOUND_OF_PROPERTY_RANGE"
                 :LIFECYCLE_INTEGRATION_SCHEMA
  (("classified"
    :RANGE
    PROPERTY
    :SOURCE
    CLASSIFICATION
    :REDEFINITION-OF
    (CLASSIFICATION "classified")
    :OPTIONAL
    NIL)
   ("classifier"
    :RANGE
    PROPERTY_RANGE
    :SOURCE
    CLASSIFICATION
    :REDEFINITION-OF
    (CLASSIFICATION "classifier")
    :OPTIONAL
    NIL)))

(SETF (SUBTYPE-OF (FIND-CLASS 'LOWER_BOUND_OF_PROPERTY_RANGE))
      '(CLASSIFICATION))


(DEFENTITY-CLASS "MATERIALIZED_PHYSICAL_OBJECT"
                 :LIFECYCLE_INTEGRATION_SCHEMA
  NIL)

(SETF (SUBTYPE-OF (FIND-CLASS 'MATERIALIZED_PHYSICAL_OBJECT))
      '(PHYSICAL_OBJECT))


(DEFENTITY-CLASS "MULTIDIMENSIONAL_NUMBER"
                 :LIFECYCLE_INTEGRATION_SCHEMA
  NIL)

(SETF (SUBTYPE-OF (FIND-CLASS 'MULTIDIMENSIONAL_NUMBER))
      '(ARITHMETIC_NUMBER MULTIDIMENSIONAL_OBJECT))


(DEFENTITY-CLASS "MULTIDIMENSIONAL_NUMBER_SPACE"
                 :LIFECYCLE_INTEGRATION_SCHEMA
  NIL)

(SETF (SUBTYPE-OF (FIND-CLASS 'MULTIDIMENSIONAL_NUMBER_SPACE))
      '(NUMBER_SPACE MULTIDIMENSIONAL_OBJECT))


(DEFENTITY-CLASS "MULTIDIMENSIONAL_OBJECT"
                 :LIFECYCLE_INTEGRATION_SCHEMA
  (("elements"
    :RANGE
    (MAKE-INSTANCE 'LIST-TYP
                   :L-BOUND
                   1
                   :U-BOUND
                   :?
                   :BASE-TYPE
                   'THING
                   :UNIQUE
                   NIL)
    :SOURCE
    MULTIDIMENSIONAL_OBJECT
    :OPTIONAL
    NIL)
   ("position"
    :RANGE
    (MAKE-INSTANCE 'LIST-TYP
                   :L-BOUND
                   1
                   :U-BOUND
                   :?
                   :BASE-TYPE
                   (MAKE-INSTANCE 'INTEGER-TYP)
                   :UNIQUE
                   NIL)
    :SOURCE
    MULTIDIMENSIONAL_OBJECT
    :OPTIONAL
    T)))

(SETF (SUBTYPE-OF (FIND-CLASS 'MULTIDIMENSIONAL_OBJECT))
      '(ABSTRACT_OBJECT))


(DEFENTITY-CLASS "MULTIDIMENSIONAL_PROPERTY"
                 :LIFECYCLE_INTEGRATION_SCHEMA
  NIL)

(SETF (SUBTYPE-OF (FIND-CLASS 'MULTIDIMENSIONAL_PROPERTY))
      '(PROPERTY MULTIDIMENSIONAL_OBJECT))


(DEFENTITY-CLASS "MULTIDIMENSIONAL_PROPERTY_SPACE"
                 :LIFECYCLE_INTEGRATION_SCHEMA
  NIL)

(SETF (SUBTYPE-OF (FIND-CLASS 'MULTIDIMENSIONAL_PROPERTY_SPACE))
      '(PROPERTY_SPACE MULTIDIMENSIONAL_OBJECT))


(DEFENTITY-CLASS "MULTIDIMENSIONAL_SCALE" :LIFECYCLE_INTEGRATION_SCHEMA
  NIL)

(SETF (SUBTYPE-OF (FIND-CLASS 'MULTIDIMENSIONAL_SCALE))
      '(SCALE MULTIDIMENSIONAL_OBJECT))


(DEFENTITY-CLASS "NAMESPACE" :LIFECYCLE_INTEGRATION_SCHEMA
  (("class_of_part"
    :RANGE
    CLASS_OF_INFORMATION_REPRESENTATION
    :SOURCE
    CLASS_OF_COMPOSITION_OF_INDIVIDUAL
    :REDEFINITION-OF
    (CLASS_OF_COMPOSITION_OF_INDIVIDUAL "class_of_part")
    :OPTIONAL
    NIL)
   ("class_of_whole"
    :RANGE
    CLASS_OF_INFORMATION_REPRESENTATION
    :SOURCE
    CLASS_OF_COMPOSITION_OF_INDIVIDUAL
    :REDEFINITION-OF
    (CLASS_OF_COMPOSITION_OF_INDIVIDUAL "class_of_whole")
    :OPTIONAL
    NIL)))

(SETF (SUBTYPE-OF (FIND-CLASS 'NAMESPACE))
      '(CLASS_OF_ARRANGEMENT_OF_INDIVIDUAL))
(SETF (EXPO::ABSTRACT-P (FIND-CLASS 'NAMESPACE)) T)


(DEFENTITY-CLASS "NUMBER_RANGE" :LIFECYCLE_INTEGRATION_SCHEMA NIL)

(SETF (SUBTYPE-OF (FIND-CLASS 'NUMBER_RANGE)) '(NUMBER_SPACE))


(DEFENTITY-CLASS "NUMBER_SPACE" :LIFECYCLE_INTEGRATION_SCHEMA NIL)

(SETF (SUBTYPE-OF (FIND-CLASS 'NUMBER_SPACE)) '(CLASS_OF_NUMBER))


(DEFENTITY-CLASS "OTHER_RELATIONSHIP" :LIFECYCLE_INTEGRATION_SCHEMA
  (("end_1" :RANGE THING :SOURCE OTHER_RELATIONSHIP :OPTIONAL NIL)
   ("end_2" :RANGE THING :SOURCE OTHER_RELATIONSHIP :OPTIONAL NIL)))

(SETF (SUBTYPE-OF (FIND-CLASS 'OTHER_RELATIONSHIP)) '(RELATIONSHIP))


(DEFENTITY-CLASS "PARTICIPATING_ROLE_AND_DOMAIN"
                 :LIFECYCLE_INTEGRATION_SCHEMA
  NIL)

(SETF (SUBTYPE-OF (FIND-CLASS 'PARTICIPATING_ROLE_AND_DOMAIN))
      '(ROLE_AND_DOMAIN CLASS_OF_INDIVIDUAL))


(DEFENTITY-CLASS "PARTICIPATION" :LIFECYCLE_INTEGRATION_SCHEMA
  (("whole"
    :RANGE
    ACTIVITY
    :SOURCE
    COMPOSITION_OF_INDIVIDUAL
    :REDEFINITION-OF
    (COMPOSITION_OF_INDIVIDUAL "whole")
    :OPTIONAL
    NIL)))

(SETF (SUBTYPE-OF (FIND-CLASS 'PARTICIPATION))
      '(COMPOSITION_OF_INDIVIDUAL))


(DEFENTITY-CLASS "PERIOD_IN_TIME" :LIFECYCLE_INTEGRATION_SCHEMA NIL)

(SETF (SUBTYPE-OF (FIND-CLASS 'PERIOD_IN_TIME)) '(POSSIBLE_INDIVIDUAL))


(DEFENTITY-CLASS "PHASE" :LIFECYCLE_INTEGRATION_SCHEMA NIL)

(SETF (SUBTYPE-OF (FIND-CLASS 'PHASE)) '(CLASS_OF_ARRANGED_INDIVIDUAL))


(DEFENTITY-CLASS "PHYSICAL_OBJECT" :LIFECYCLE_INTEGRATION_SCHEMA NIL)

(SETF (SUBTYPE-OF (FIND-CLASS 'PHYSICAL_OBJECT)) '(POSSIBLE_INDIVIDUAL))


(DEFENTITY-CLASS "POINT_IN_TIME" :LIFECYCLE_INTEGRATION_SCHEMA NIL)

(SETF (SUBTYPE-OF (FIND-CLASS 'POINT_IN_TIME)) '(EVENT))


(DEFENTITY-CLASS "POSSIBLE_INDIVIDUAL" :LIFECYCLE_INTEGRATION_SCHEMA
  NIL)

(SETF (SUBTYPE-OF (FIND-CLASS 'POSSIBLE_INDIVIDUAL)) '(THING))


(DEFENTITY-CLASS "POSSIBLE_ROLE_AND_DOMAIN"
                 :LIFECYCLE_INTEGRATION_SCHEMA
  (("played"
    :RANGE
    ROLE_AND_DOMAIN
    :SOURCE
    POSSIBLE_ROLE_AND_DOMAIN
    :OPTIONAL
    NIL)
   ("player"
    :RANGE
    POSSIBLE_INDIVIDUAL
    :SOURCE
    POSSIBLE_ROLE_AND_DOMAIN
    :OPTIONAL
    NIL)))

(SETF (SUBTYPE-OF (FIND-CLASS 'POSSIBLE_ROLE_AND_DOMAIN))
      '(RELATIONSHIP))


(DEFENTITY-CLASS "PROPERTY" :LIFECYCLE_INTEGRATION_SCHEMA NIL)

(SETF (SUBTYPE-OF (FIND-CLASS 'PROPERTY)) '(CLASS_OF_INDIVIDUAL))


(DEFENTITY-CLASS "PROPERTY_FOR_SHAPE_DIMENSION"
                 :LIFECYCLE_INTEGRATION_SCHEMA
  (("property"
    :RANGE
    PROPERTY
    :SOURCE
    PROPERTY_FOR_SHAPE_DIMENSION
    :OPTIONAL
    NIL)
   ("shape_dimension"
    :RANGE
    SHAPE_DIMENSION
    :SOURCE
    PROPERTY_FOR_SHAPE_DIMENSION
    :OPTIONAL
    NIL)))

(SETF (SUBTYPE-OF (FIND-CLASS 'PROPERTY_FOR_SHAPE_DIMENSION))
      '(CLASS_OF_RELATIONSHIP))


(DEFENTITY-CLASS "PROPERTY_QUANTIFICATION"
                 :LIFECYCLE_INTEGRATION_SCHEMA
  (("input"
    :RANGE
    PROPERTY
    :SOURCE
    FUNCTIONAL_MAPPING
    :REDEFINITION-OF
    (FUNCTIONAL_MAPPING "input")
    :OPTIONAL
    NIL)
   ("result"
    :RANGE
    ARITHMETIC_NUMBER
    :SOURCE
    FUNCTIONAL_MAPPING
    :REDEFINITION-OF
    (FUNCTIONAL_MAPPING "result")
    :OPTIONAL
    NIL)))

(SETF (SUBTYPE-OF (FIND-CLASS 'PROPERTY_QUANTIFICATION))
      '(FUNCTIONAL_MAPPING))


(DEFENTITY-CLASS "PROPERTY_RANGE" :LIFECYCLE_INTEGRATION_SCHEMA NIL)

(SETF (SUBTYPE-OF (FIND-CLASS 'PROPERTY_RANGE)) '(PROPERTY_SPACE))


(DEFENTITY-CLASS "PROPERTY_SPACE" :LIFECYCLE_INTEGRATION_SCHEMA NIL)

(SETF (SUBTYPE-OF (FIND-CLASS 'PROPERTY_SPACE)) '(CLASS_OF_PROPERTY))


(DEFENTITY-CLASS "PROPERTY_SPACE_FOR_CLASS_OF_SHAPE_DIMENSION"
                 :LIFECYCLE_INTEGRATION_SCHEMA
  (("class_of_shape_dimension"
    :RANGE
    CLASS_OF_SHAPE_DIMENSION
    :SOURCE
    PROPERTY_SPACE_FOR_CLASS_OF_SHAPE_DIMENSION
    :OPTIONAL
    NIL)
   ("property_space"
    :RANGE
    PROPERTY_SPACE
    :SOURCE
    PROPERTY_SPACE_FOR_CLASS_OF_SHAPE_DIMENSION
    :OPTIONAL
    NIL)))

(SETF (SUBTYPE-OF (FIND-CLASS 'PROPERTY_SPACE_FOR_CLASS_OF_SHAPE_DIMENSION))
      '(CLASS_OF_CLASS_OF_RELATIONSHIP))


(DEFENTITY-CLASS "REAL_NUMBER" :LIFECYCLE_INTEGRATION_SCHEMA NIL)

(SETF (SUBTYPE-OF (FIND-CLASS 'REAL_NUMBER)) '(ARITHMETIC_NUMBER))


(DEFENTITY-CLASS "RECOGNITION" :LIFECYCLE_INTEGRATION_SCHEMA
  (("recognized" :RANGE THING :SOURCE RECOGNITION :OPTIONAL NIL)
   ("recognizing" :RANGE ACTIVITY :SOURCE RECOGNITION :OPTIONAL NIL)))

(SETF (SUBTYPE-OF (FIND-CLASS 'RECOGNITION)) '(RELATIONSHIP))


(DEFENTITY-CLASS "RELATIONSHIP" :LIFECYCLE_INTEGRATION_SCHEMA NIL)

(SETF (SUBTYPE-OF (FIND-CLASS 'RELATIONSHIP)) '(ABSTRACT_OBJECT))
(SETF (EXPO::ABSTRACT-P (FIND-CLASS 'RELATIONSHIP)) T)


(DEFENTITY-CLASS "RELATIVE_LOCATION" :LIFECYCLE_INTEGRATION_SCHEMA
  (("located"
    :RANGE
    POSSIBLE_INDIVIDUAL
    :SOURCE
    RELATIVE_LOCATION
    :OPTIONAL
    NIL)
   ("locator"
    :RANGE
    POSSIBLE_INDIVIDUAL
    :SOURCE
    RELATIVE_LOCATION
    :OPTIONAL
    NIL)))

(SETF (SUBTYPE-OF (FIND-CLASS 'RELATIVE_LOCATION)) '(RELATIONSHIP))


(DEFENTITY-CLASS "REPRESENTATION_FORM" :LIFECYCLE_INTEGRATION_SCHEMA
  NIL)

(SETF (SUBTYPE-OF (FIND-CLASS 'REPRESENTATION_FORM))
      '(CLASS_OF_CLASS_OF_INFORMATION_REPRESENTATION))


(DEFENTITY-CLASS "REPRESENTATION_OF_GREGORIAN_DATE_AND_UTC_TIME"
                 :LIFECYCLE_INTEGRATION_SCHEMA
  (("year"
    :RANGE
    (MAKE-INSTANCE 'INTEGER-TYP)
    :SOURCE
    REPRESENTATION_OF_GREGORIAN_DATE_AND_UTC_TIME
    :OPTIONAL
    NIL)
   ("month"
    :RANGE
    (MAKE-INSTANCE 'INTEGER-TYP)
    :SOURCE
    REPRESENTATION_OF_GREGORIAN_DATE_AND_UTC_TIME
    :OPTIONAL
    T)
   ("day"
    :RANGE
    (MAKE-INSTANCE 'INTEGER-TYP)
    :SOURCE
    REPRESENTATION_OF_GREGORIAN_DATE_AND_UTC_TIME
    :OPTIONAL
    T)
   ("hour"
    :RANGE
    (MAKE-INSTANCE 'INTEGER-TYP)
    :SOURCE
    REPRESENTATION_OF_GREGORIAN_DATE_AND_UTC_TIME
    :OPTIONAL
    T)
   ("minute"
    :RANGE
    (MAKE-INSTANCE 'INTEGER-TYP)
    :SOURCE
    REPRESENTATION_OF_GREGORIAN_DATE_AND_UTC_TIME
    :OPTIONAL
    T)
   ("second"
    :RANGE
    (MAKE-INSTANCE 'REAL-TYP)
    :SOURCE
    REPRESENTATION_OF_GREGORIAN_DATE_AND_UTC_TIME
    :OPTIONAL
    T)))

(SETF (SUBTYPE-OF (FIND-CLASS 'REPRESENTATION_OF_GREGORIAN_DATE_AND_UTC_TIME))
      '(CLASS_OF_INFORMATION_REPRESENTATION))

(DEFDOMAIN-RULES "REPRESENTATION_OF_GREGORIAN_DATE_AND_UTC_TIME"
  ("valid_month"
   (EXPRESS-AND (EXPRESS-<= 1 (%MONTH INSTANCE NIL))
                (EXPRESS-<= (%MONTH INSTANCE NIL) 12)))
  ("valid_day"
   (EXPRESS-AND (EXPRESS-<= 1 (%DAY INSTANCE NIL))
                (EXPRESS-<= (%DAY INSTANCE NIL) 31)))
  ("valid_hour"
   (EXPRESS-AND (EXPRESS-<= 0 (%HOUR INSTANCE NIL))
                (EXPRESS-<= (%HOUR INSTANCE NIL) 23)))
  ("valid_minute"
   (EXPRESS-AND (EXPRESS-<= 0 (%MINUTE INSTANCE NIL))
                (EXPRESS-<= (%MINUTE INSTANCE NIL) 59)))
  ("valid_second"
   (EXPRESS-AND (EXPRESS-<= 0 (%SECOND INSTANCE NIL))
                (EXPRESS-< (%SECOND INSTANCE NIL) 61))))


(DEFENTITY-CLASS "REPRESENTATION_OF_THING"
                 :LIFECYCLE_INTEGRATION_SCHEMA
  (("represented"
    :RANGE
    THING
    :SOURCE
    REPRESENTATION_OF_THING
    :OPTIONAL
    NIL)
   ("sign"
    :RANGE
    POSSIBLE_INDIVIDUAL
    :SOURCE
    REPRESENTATION_OF_THING
    :OPTIONAL
    NIL)))

(SETF (SUBTYPE-OF (FIND-CLASS 'REPRESENTATION_OF_THING))
      '(RELATIONSHIP))


(DEFENTITY-CLASS "RESPONSIBILITY_FOR_REPRESENTATION"
                 :LIFECYCLE_INTEGRATION_SCHEMA
  (("controlled"
    :RANGE
    REPRESENTATION_OF_THING
    :SOURCE
    RESPONSIBILITY_FOR_REPRESENTATION
    :OPTIONAL
    NIL)
   ("controller"
    :RANGE
    POSSIBLE_INDIVIDUAL
    :SOURCE
    RESPONSIBILITY_FOR_REPRESENTATION
    :OPTIONAL
    NIL)))

(SETF (SUBTYPE-OF (FIND-CLASS 'RESPONSIBILITY_FOR_REPRESENTATION))
      '(RELATIONSHIP))


(DEFENTITY-CLASS "RIGHT_NAMESPACE" :LIFECYCLE_INTEGRATION_SCHEMA NIL)

(SETF (SUBTYPE-OF (FIND-CLASS 'RIGHT_NAMESPACE)) '(NAMESPACE))


(DEFENTITY-CLASS "ROLE" :LIFECYCLE_INTEGRATION_SCHEMA NIL)

(SETF (SUBTYPE-OF (FIND-CLASS 'ROLE)) '(ROLE_AND_DOMAIN))


(DEFENTITY-CLASS "ROLE_AND_DOMAIN" :LIFECYCLE_INTEGRATION_SCHEMA NIL)

(SETF (SUBTYPE-OF (FIND-CLASS 'ROLE_AND_DOMAIN)) '(CLASS))


(DEFENTITY-CLASS "SCALE" :LIFECYCLE_INTEGRATION_SCHEMA
  (("codomain"
    :RANGE
    NUMBER_SPACE
    :SOURCE
    CLASS_OF_FUNCTIONAL_MAPPING
    :REDEFINITION-OF
    (CLASS_OF_FUNCTIONAL_MAPPING "codomain")
    :OPTIONAL
    NIL)
   ("domain"
    :RANGE
    PROPERTY_SPACE
    :SOURCE
    CLASS_OF_FUNCTIONAL_MAPPING
    :REDEFINITION-OF
    (CLASS_OF_FUNCTIONAL_MAPPING "domain")
    :OPTIONAL
    NIL)))

(SETF (SUBTYPE-OF (FIND-CLASS 'SCALE))
      '(CLASS_OF_ISOMORPHIC_FUNCTIONAL_MAPPING))


(DEFENTITY-CLASS "SHAPE" :LIFECYCLE_INTEGRATION_SCHEMA NIL)

(SETF (SUBTYPE-OF (FIND-CLASS 'SHAPE)) '(PROPERTY))


(DEFENTITY-CLASS "SHAPE_DIMENSION" :LIFECYCLE_INTEGRATION_SCHEMA NIL)

(SETF (SUBTYPE-OF (FIND-CLASS 'SHAPE_DIMENSION))
      '(CLASS_OF_CLASS_OF_INDIVIDUAL))


(DEFENTITY-CLASS "SINGLE_PROPERTY_DIMENSION"
                 :LIFECYCLE_INTEGRATION_SCHEMA
  NIL)

(SETF (SUBTYPE-OF (FIND-CLASS 'SINGLE_PROPERTY_DIMENSION))
      '(PROPERTY_SPACE))


(DEFENTITY-CLASS "SPATIAL_LOCATION" :LIFECYCLE_INTEGRATION_SCHEMA NIL)

(SETF (SUBTYPE-OF (FIND-CLASS 'SPATIAL_LOCATION)) '(PHYSICAL_OBJECT))


(DEFENTITY-CLASS "SPECIALIZATION" :LIFECYCLE_INTEGRATION_SCHEMA
  (("subclass" :RANGE CLASS :SOURCE SPECIALIZATION :OPTIONAL NIL)
   ("superclass" :RANGE CLASS :SOURCE SPECIALIZATION :OPTIONAL NIL)))

(SETF (SUBTYPE-OF (FIND-CLASS 'SPECIALIZATION)) '(RELATIONSHIP))


(DEFENTITY-CLASS "SPECIALIZATION_BY_DOMAIN"
                 :LIFECYCLE_INTEGRATION_SCHEMA
  (("subclass"
    :RANGE
    ROLE_AND_DOMAIN
    :SOURCE
    SPECIALIZATION
    :REDEFINITION-OF
    (SPECIALIZATION "subclass")
    :OPTIONAL
    NIL)))

(SETF (SUBTYPE-OF (FIND-CLASS 'SPECIALIZATION_BY_DOMAIN))
      '(SPECIALIZATION))


(DEFENTITY-CLASS "SPECIALIZATION_BY_ROLE" :LIFECYCLE_INTEGRATION_SCHEMA
  (("subclass"
    :RANGE
    ROLE_AND_DOMAIN
    :SOURCE
    SPECIALIZATION
    :REDEFINITION-OF
    (SPECIALIZATION "subclass")
    :OPTIONAL
    NIL)
   ("superclass"
    :RANGE
    ROLE
    :SOURCE
    SPECIALIZATION
    :REDEFINITION-OF
    (SPECIALIZATION "superclass")
    :OPTIONAL
    NIL)))

(SETF (SUBTYPE-OF (FIND-CLASS 'SPECIALIZATION_BY_ROLE))
      '(SPECIALIZATION))


(DEFENTITY-CLASS "SPECIALIZATION_OF_INDIVIDUAL_DIMENSION_FROM_PROPERTY"
                 :LIFECYCLE_INTEGRATION_SCHEMA
  (("subclass"
    :RANGE
    INDIVIDUAL_DIMENSION
    :SOURCE
    SPECIALIZATION
    :REDEFINITION-OF
    (SPECIALIZATION "subclass")
    :OPTIONAL
    NIL)
   ("superclass"
    :RANGE
    PROPERTY
    :SOURCE
    SPECIALIZATION
    :REDEFINITION-OF
    (SPECIALIZATION "superclass")
    :OPTIONAL
    NIL)))

(SETF (SUBTYPE-OF (FIND-CLASS 'SPECIALIZATION_OF_INDIVIDUAL_DIMENSION_FROM_PROPERTY))
      '(SPECIALIZATION))


(DEFENTITY-CLASS "STATUS" :LIFECYCLE_INTEGRATION_SCHEMA NIL)

(SETF (SUBTYPE-OF (FIND-CLASS 'STATUS)) '(CLASS_OF_INDIVIDUAL))


(DEFENTITY-CLASS "STREAM" :LIFECYCLE_INTEGRATION_SCHEMA NIL)

(SETF (SUBTYPE-OF (FIND-CLASS 'STREAM)) '(PHYSICAL_OBJECT))


(DEFENTITY-CLASS "TEMPORAL_BOUNDING" :LIFECYCLE_INTEGRATION_SCHEMA
  (("part"
    :RANGE
    EVENT
    :SOURCE
    COMPOSITION_OF_INDIVIDUAL
    :REDEFINITION-OF
    (COMPOSITION_OF_INDIVIDUAL "part")
    :OPTIONAL
    NIL)))

(SETF (SUBTYPE-OF (FIND-CLASS 'TEMPORAL_BOUNDING))
      '(COMPOSITION_OF_INDIVIDUAL))
(SETF (EXPO::ABSTRACT-P (FIND-CLASS 'TEMPORAL_BOUNDING)) T)


(DEFENTITY-CLASS "TEMPORAL_SEQUENCE" :LIFECYCLE_INTEGRATION_SCHEMA
  (("predecessor"
    :RANGE
    POSSIBLE_INDIVIDUAL
    :SOURCE
    TEMPORAL_SEQUENCE
    :OPTIONAL
    NIL)
   ("successor"
    :RANGE
    POSSIBLE_INDIVIDUAL
    :SOURCE
    TEMPORAL_SEQUENCE
    :OPTIONAL
    NIL)))

(SETF (SUBTYPE-OF (FIND-CLASS 'TEMPORAL_SEQUENCE)) '(RELATIONSHIP))


(DEFENTITY-CLASS "TEMPORAL_WHOLE_PART" :LIFECYCLE_INTEGRATION_SCHEMA
  NIL)

(SETF (SUBTYPE-OF (FIND-CLASS 'TEMPORAL_WHOLE_PART))
      '(COMPOSITION_OF_INDIVIDUAL))


(DEFENTITY-CLASS "THING" :LIFECYCLE_INTEGRATION_SCHEMA
  (("id"
    :RANGE
    (MAKE-INSTANCE 'STRING-TYP)
    :SOURCE
    THING
    :OPTIONAL
    NIL)
   ("record_copy_created"
    :RANGE
    REPRESENTATION_OF_GREGORIAN_DATE_AND_UTC_TIME
    :SOURCE
    THING
    :OPTIONAL
    T)
   ("record_created"
    :RANGE
    REPRESENTATION_OF_GREGORIAN_DATE_AND_UTC_TIME
    :SOURCE
    THING
    :OPTIONAL
    T)
   ("record_creator"
    :RANGE
    POSSIBLE_INDIVIDUAL
    :SOURCE
    THING
    :OPTIONAL
    T)
   ("record_logically_deleted"
    :RANGE
    REPRESENTATION_OF_GREGORIAN_DATE_AND_UTC_TIME
    :SOURCE
    THING
    :OPTIONAL
    T)
   ("why_deleted"
    :RANGE
    CLASS_OF_INFORMATION_REPRESENTATION
    :SOURCE
    THING
    :OPTIONAL
    T)))
(SETF (EXPO::ABSTRACT-P (FIND-CLASS 'THING)) T)


(DEFENTITY-CLASS "UNION_OF_SET_OF_CLASS" :LIFECYCLE_INTEGRATION_SCHEMA
  (("input"
    :RANGE
    ENUMERATED_SET_OF_CLASS
    :SOURCE
    FUNCTIONAL_MAPPING
    :REDEFINITION-OF
    (FUNCTIONAL_MAPPING "input")
    :OPTIONAL
    NIL)
   ("result"
    :RANGE
    CLASS
    :SOURCE
    FUNCTIONAL_MAPPING
    :REDEFINITION-OF
    (FUNCTIONAL_MAPPING "result")
    :OPTIONAL
    NIL)))

(SETF (SUBTYPE-OF (FIND-CLASS 'UNION_OF_SET_OF_CLASS))
      '(FUNCTIONAL_MAPPING))


(DEFENTITY-CLASS "UPPER_BOUND_OF_NUMBER_RANGE"
                 :LIFECYCLE_INTEGRATION_SCHEMA
  (("classified"
    :RANGE
    ARITHMETIC_NUMBER
    :SOURCE
    CLASSIFICATION
    :REDEFINITION-OF
    (CLASSIFICATION "classified")
    :OPTIONAL
    NIL)
   ("classifier"
    :RANGE
    NUMBER_RANGE
    :SOURCE
    CLASSIFICATION
    :REDEFINITION-OF
    (CLASSIFICATION "classifier")
    :OPTIONAL
    NIL)))

(SETF (SUBTYPE-OF (FIND-CLASS 'UPPER_BOUND_OF_NUMBER_RANGE))
      '(CLASSIFICATION))


(DEFENTITY-CLASS "UPPER_BOUND_OF_PROPERTY_RANGE"
                 :LIFECYCLE_INTEGRATION_SCHEMA
  (("classified"
    :RANGE
    PROPERTY
    :SOURCE
    CLASSIFICATION
    :REDEFINITION-OF
    (CLASSIFICATION "classified")
    :OPTIONAL
    NIL)
   ("classifier"
    :RANGE
    PROPERTY_RANGE
    :SOURCE
    CLASSIFICATION
    :REDEFINITION-OF
    (CLASSIFICATION "classifier")
    :OPTIONAL
    NIL)))

(SETF (SUBTYPE-OF (FIND-CLASS 'UPPER_BOUND_OF_PROPERTY_RANGE))
      '(CLASSIFICATION))


(DEFENTITY-CLASS "USAGE_OF_REPRESENTATION"
                 :LIFECYCLE_INTEGRATION_SCHEMA
  (("used"
    :RANGE
    REPRESENTATION_OF_THING
    :SOURCE
    USAGE_OF_REPRESENTATION
    :OPTIONAL
    NIL)
   ("user"
    :RANGE
    POSSIBLE_INDIVIDUAL
    :SOURCE
    USAGE_OF_REPRESENTATION
    :OPTIONAL
    NIL)))

(SETF (SUBTYPE-OF (FIND-CLASS 'USAGE_OF_REPRESENTATION))
      '(RELATIONSHIP))


(DEFENTITY-CLASS "WHOLE_LIFE_INDIVIDUAL" :LIFECYCLE_INTEGRATION_SCHEMA
  NIL)

(SETF (SUBTYPE-OF (FIND-CLASS 'WHOLE_LIFE_INDIVIDUAL))
      '(POSSIBLE_INDIVIDUAL))




;;;=================
;;; GlobalRules
;;;=================


;;;=================
;;; Functions
;;;=================

;;; END OF OUTPUT